### ISSUE TITLE
input engine

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#1]
- Compare input engine (scim, ibus, xvnkb, bogo)
- Suggest the best engine
- Suggest the features needed to be improved

**Comment by NgoHuy** [comment]
#### Compare input engine
- **Ibus**: 
  - **Advantage**: easy to install, configure and support multi-languages
  - **Disadvantage**: no configure for different windows ( share the same input engine as default ). Making user annoy because of preedit feature. 
  - **Engine**:
    - _Ibus-unikey_: preedit feature, checking non-Vietnamese words. Stable and Avaiable on Arch community repo.
    - _Ibus-Bogo_: disable preedit feature, using dictionary to define words. Checking non-Vietnamese feature's unstable. Unstables and Avaiable on AUR repo. Using Python for source code.
- **Scim**:
  - **Advantage**: easy to install and support multi-languages.
  - **Disadvantage**: difficult to configure. Unstables and out of date.
  - **Engine**
    - _Scim-unikey_
- **Xvnkb**:
  - **Advantage**: only for geek users.
  - **Disadvantage**: difficult to install and configure. No checking non-Vietnamese words.

#### Sugest the best engine
- **Ibus-bogo**: disable preedit feature. Need to improve non-Vietnamese checking. Developers will commit to fix this bug.

**Comment by lewtds** [comment]
IBus and SCIM are input method managers/multiplexers and they come with unikey flavors and BoGo for IBus. xvnkb wouldn't be so hard to install if it comes pre-installed by default.

I think ibus-bogo is the way to go (please feel free to ignore my opinions as I'm the main developer) for being relatively fresh, actively developed, easy to install/configure and open to changes. The obvious downside for this choice would be PySide (used for config GUI) being only available from AUR.

Btw, in later versions of ibus-bogo, non-Vietnamese typing will come as a helper feature in form of a drop down option while typing and not the default behavior. And we don't _disable_ preediting, we strive hard not to use it from the very start.

**Comment by NgoHuy** [comment]
Xvnkb requires ld-preload. And it's difficult for users to change input method ( vni,telex) or remove from the system. We will build PySide on our server and provide binary if neccessary ( installed as default package). If Ibus-bogo has checking non-Vietnamese feature, it shoud be default feature as unikey returns English if not Vietnamese words. 
_Preediting's not disabled_  I will remember this :-)

**Comment by lewtds** [comment]
I think it's best to make the original keystrokes an optional selectable choice shown when typing non-VNmese as it would be impossible for users to determine whether a keystroke sequence like `s+y+s+t+e+m` would yield "system" or "sýtem" after they press the spacebar as in the current ibus-unikey's implementation.

**Comment by NgoHuy** [comment]
I see :-)

**Comment by icy** [comment]
Huy có thể viết bằng tiếng Việt cho khỏe. Huy cần so sánh tốt hơn, về
nguyên lý thiết kế, lập trình, lý do,...

Tất nhiên mình sẽ chọn bộ gõ nào cũng được đứng từ phía người dùng. Các
bộ gõ chỉ nên đề xuất và cho phép người dùng lựa chọn. Ví dụ kiểu gõ
Telex trên nhiều bộ gõ rất bất tiện khi định nghĩa lại [ và ] hoặc w
(thành ư). Điều này KHÔNG NÊN làm từ bộ gõ, mà nên làm từ phía người
dùng.

Cũng cần chỉ ra cách định nghĩa bảng gõ mới , kiểu gõ tốc ký,
telex++, .... ở phía người dùng (Unikey chằng hạn có danh sách các từ
gõ tắt do người dùng tự định nghĩa).

Mình ủng hộ Bongo, tuy nhiên cần chú ý các yêu cầu cơ bản sau
- hỗ trợ Anh, Việt (và có thể Pháp)
- chỉ cung cấp phương pháp và có thể phương pháp mặc định, để người
  dùng nhiều lựa chọn hơn (ví dụ về cửa sổ preedit hòan tòan vô tích sự
  với mình)
- cho phép người dùng nhiều khả năng tự điều chỉnh bộ gõ

On Mon, 25 Feb 2013 06:36:04 -0800
Ngô Huy notifications@github.com wrote:

> Compare input engine
> - **Ibus**: 
>   - **Advantage**: easy to install, configure and support
>     multi-languages
>   - **Disadvantage**: no configure for different windows ( share the
>     same input engine as default ). Making user annoy because of preedit
>     feature. 
>   - **Engine**:
>     - _Ibus-unikey_: preedit feature, checking non-Vietnamese words.
>       Stable and Avaiable on Arch community repo.
>     - _Ibus-Bogo_: disable preedit feature, using dictionary to
>       define words. Checking non-Vietnamese feature's unstable. Unstables
>       and Avaiable on AUR repo. 
> - **Scim**:
>   - **Advantage**: easy to install and support multi-languages.
>   - **Disadvantage**: difficult to configure. Unstables and out of
>     date.
>   - **Engine**
>     - _Scim-unikey_
> - **Xvnkb**:
>   - **Advantage**: only for geek users.
>   - **Disadvantage**: difficult to install and configure. No checking
>     non-Vietnamese words. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/archlinuxvn/kenlinux/issues/1#issuecomment-14044828

## 

I am ... 5 dog years old.

**Comment by lewtds** [comment]
Vào 10:25 Ngày 03 tháng 3 năm 2013, icy notifications@github.com đã viết:

> Tất nhiên mình sẽ chọn bộ gõ nào cũng được đứng từ phía người dùng. Các
> bộ gõ chỉ nên đề xuất và cho phép người dùng lựa chọn. Ví dụ kiểu gõ
> Telex trên nhiều bộ gõ rất bất tiện khi định nghĩa lại [ và ] hoặc w
> (thành ư). Điều này KHÔNG NÊN làm từ bộ gõ, mà nên làm từ phía người
> dùng.

Các bộ gõ đều có các chế độ TELEX khác nhau. VD trong Unikey thì Simple Telex
là TELEX gốc, Simple Telex 2 là TELEX có thêm chữ w -> ư, Telex thì có thêm ][.

Nhưng em cũng thấy ý kiến này của bác rất hay. Chỉ nên có một Telex và
các tính năng
kia ở dạng optional. Tuy nhiên, do quá trình sử dụng Telex có tính
năng phụ trợ của
phần lớn người dùng đã quá lâu nên người ta sẽ cho rằng đó là một phần không thể
thiếu của Telex nên nếu làm theo phương án này, BoGo cũng sẽ để tính
năng optional
này bật sẵn.

> Cũng cần chỉ ra cách định nghĩa bảng gõ mới , kiểu gõ tốc ký,
> telex++, .... ở phía người dùng (Unikey chằng hạn có danh sách các từ
> gõ tắt do người dùng tự định nghĩa).

Có thể định nghĩa kiểu gõ mới trong file config, chưa có GUI thôi. Gõ
tắt đang thực hiện.

> Mình ủng hộ Bongo, tuy nhiên cần chú ý các yêu cầu cơ bản sau
> - hỗ trợ Anh, Việt (và có thể Pháp)

Bộ gõ tiếng Việt thì gõ tiếng Việt là ưu tiên hàng đầu. BoGo cũng có
thể gõ tiếng Anh chen
lẫn tiếng Việt. Còn tiếng Pháp thì em e là người dùng sẽ phải tắt BoGo
đi, sử dụng Compose Key
hoặc French layout.

> - chỉ cung cấp phương pháp và có thể phương pháp mặc định, để người
>   dùng nhiều lựa chọn hơn (ví dụ về cửa sổ preedit hòan tòan vô tích sự
>   với mình)

Không hiểu ý này của bác.

> - cho phép người dùng nhiều khả năng tự điều chỉnh bộ gõ

BoGo cố gắng cho người dùng nhiều khả năng tùy chỉnh nhất có thể. Tuy
nhiên, nhu cầu của người
sử dụng có thể sẽ khác nhiều so với nhu cầu của tác giả. Vậy nên người
dùng muốn tùy chỉnh đến
đâu phải trao đổi thì tác giả mới biết.

Rất cảm ơn các ý kiến của bác.

**Comment by lewtds** [comment]
Những vấn đề về BoGo mong các bác bàn trên issue của BoGo để nhóm phát triển BoGo dễ theo dõi hơn.
