### ISSUE TITLE
Điều chỉnh giao diện trang web cho thiết bị mobile

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#102]
Hiện tại, cỡ chữ rất nhỏ của trang web khi xem trên iphone khiến người đọc mệt mỏi và chuyển trang không chính xác.

**Comment by tdan** [comment]
Xin chào dự án, mình đã chỉnh sửa lại giao diện website để thân thiện hơn với mobile. Giao diện mới đã được test trên Nexus 4, 7 và iPhone 5.  
Link bản vá http://pastebin.com/hwmMcny2.

**Comment by thuandt** [comment]
01 - Vote ban vì khoe smartphone và tablet trá hình
02 - Pull Request trên github đi, ai đời luser gạo cội lại hem dùng git được :-1:

**Comment by tdan** [comment]
Toàn hàng đi mượn cả. Với lại tôi cũng chỉnh sửa 1 chút thôi, ko có gì nhiều nhặn để làm pull request

**Comment by icy** [comment]
Cảm ơn @tdan mình sẽ trộn vào nhánh chính sớm!

**Comment by thuandt** [comment]
@tdan ít nhiều cũng pull request được hết mà :)

**Comment by icy** [comment]
Không thể `patch` được, @tdan xem tại sao !?

```
$ patch -lp1 --dry-run< ~/df/responsive.patch.txt 
checking file content/stylesheet.css
Hunk #3 FAILED at 39.
Hunk #4 succeeded at 81 (offset 12 lines).
Hunk #5 succeeded at 131 (offset 12 lines).
Hunk #6 FAILED at 136.
Hunk #7 succeeded at 156 (offset 12 lines).
Hunk #8 succeeded at 170 (offset 12 lines).
Hunk #9 FAILED at 284.
Hunk #10 FAILED at 303.
Hunk #11 succeeded at 324 (offset 12 lines).
Hunk #12 FAILED at 392.
5 out of 12 hunks FAILED
checking file layouts/default.html
```

**Comment by icy** [comment]
@tdan: Em điều chỉnh trên nhánh `master` là nhánh chỉ dùng để điều chỉnh nội dung. Các điều chỉnh về giao diện và mã Ruby cần thực hiện trên nhánh `core`. Anh đã thử trộn và đảo lại như cũ do không phù hợp. Anh cũng đã điều chỉnh lại tài liệu để tránh vấn đề tương tự trong tương lai.
- Miếng vá của em https://github.com/TheSLinux/homepage/commit/86211ffb0762775d9312e2e58a497e9f9fdb4b08
- Và đảo lại https://github.com/TheSLinux/homepage/commit/166784e86b20b5a833d5070191118a4225671739
- Điều chỉnh trong tài liệu https://github.com/TheSLinux/homepage/commit/1179288b8d98613411fe8310aff2297fc00a0c4a

**Comment by tdan** [comment]
Vâng ạ, em sẽ rút kinh nghiệm

**Comment by icy** [comment]
@tdan : Bạn có thời gian chỉnh trên nhánh _core_ và tạo pull request nhé. Khi mình dùng mã của bạn trên nhánh _master_ thì phát sinh nhiều lỗi. Mình cũng thay đổi cỡ chữ của thanh menu để xem vừa trên Iphone (menu không bị tách thành hai dòng.)

Cảm ơn bạn nhiều.

**Comment by tdan** [comment]
vâng, em sẽ thu xếp thời gian cuối tuần này để sửa

**Comment by tdan** [comment]
@icy: Em đã chỉnh lại code, test = Responsive Design View trên FF thì thấy ok. Anh clone về, test lại rồi báo lỗi cho em nhé.
Code em commit ở trong này: https://github.com/tdan/homepage

**Comment by icy** [comment]
Cảm ơn @tdan mình sẽ xem và trộn nếu không có vấn đề gì!
