### ISSUE TITLE
Lỗi chính tả trong commit 

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#107]
Xem ví dụ https://github.com/TheSLinux/buildsystem/pull/19.patch .
- Sai: Origin Maitainer. Cần chỉnh lại: Original Maintainer
- Origin cũng cần được chỉnh lại Original ở các vị trí khác.

**Comment by NgoHuy** [comment]
chết thật hôm nọ xem commit của anh em đã sửa chỗ đó xong chưa merge với cái bản cũ, em sẽ sửa lại tòan bộ, Cảm ơn anh đã review

**Comment by icy** [comment]
note: Có 4 gói a đã merge vào trong repo chính
