### ISSUE TITLE
Chuyển (đổi) l00s5r -> l00s7r

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#108]
Do các vấn đề network của l00s5r xảy ra khá thường xuyên làm ảnh hưởng đến hệ thống nhóm thư và vài thứ khác, dự án phải chuyển các chức năng cơ bản của máy l00s5r qua máy l00s7r (phải mua thêm).

**Comment by icy** [comment]
Chờ cuối tháng này DigitalOcean có DC mới ở châu Á sẽ đăng ký một máy ;)

**Comment by icy** [comment]
DigitalOcean vẫn chưa có DC mới ở châu Á :)

Dù sao, máy mới l00s7r đã lên đàn và hoạt động chính thức. Xem thêm ở tin tức http://theslinux.org/news/2014

**Comment by l00s5r** [comment]
Ghi chú ở trên sẽ không được gửi vào nhóm thư bugs :0 Lý do là ... quên đặt cấu hình chuyển tiếp thư cho tài  khoản này !^^

**Comment by icy** [comment]
Không rõ vì lý do gì, khi đổi email thì github bắt chờ hơi lâu :D Hoặc là hàng đợi sẽ thử lại do kết nối tới `l00s5r` tạm thời bị ... bay ra ngoài?

**Comment by icy** [comment]
Đóng ticket này lại. Tập trung vấn đề "đồng bộ hai nhóm thư" ở #105.
