### ISSUE TITLE
Nhóm thư hackers bị lỗi chữ kí cuối thư

### ISSUE THREAD

**Issue by NgoHuy** [TheSLinux/gs#109]
Hiện tại, nhóm thư hackers bị một lỗi khá khó hiểu là sau dòng "Ending PGP Signature" có một dòng không thể đọc được do không phải kí tự unicode.

Ví dụ: 
N�����r��y���^�+-��$z�%��l���)�Ɗ�W����֧zf���q���b��-��%�{���0��l���rۛ���r��z����N������(�f�v�h�Ǆq���2�צ�Ǭ���r�^lp==

Mail Client ảnh hưởng: Thunderbird.

**Comment by icy** [comment]
Đây là lỗi đã biết của hệ thống _ecartis_, khi nó luôn cố gắng chèn chữ ký của nhóm thư vào cuối thư bất kể điều kiện. Dòng rồng rắn ở trên là do trình duyệt email cố giải mã phần nội dung (chữ ký nhóm thư) chưa mã hóa. 

Để giải quyết vấn đề, cần thêm vào một `header` để `ecartis` nhận diện điều kiện thêm chữ ký, ngoài ra cũng phải hiệu chỉnh phần thêm chữ ký (đoạn này viết bằng C nên mình hơi nản :D)

Thanks @NgoHuy !

**Comment by icy** [comment]
Đã fix, nhờ sử dụng bộ điều chỉnh "footer" riêng.
