### ISSUE TITLE
Môi trường staging cho trang web dự án

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#111]
cc: @tdan

Môi trường Staging cho phép xem trước các thay đổi (giao diện, bố cục) của trang web, trước khi các thay đổi được dùng chính thức cho trang web của dự án.

Cần tạo ra một nhánh riêng (staging, gồm có `contents-staging` hoặc `core-staging`), một số thành viên có thể push trực tiếp vào các nhánh này. Thông qua `pull request` các thay đổi sẽ được trộn vào nhánh chính (`core` và `master`).

**Comment by icy** [comment]
Liên quan: #102 và https://github.com/TheSLinux/homepage/pull/1

**Comment by tdan** [comment]
@icy: Em đã tạo 1 nhánh mới là core-staging trong repo; phần code chỉnh sửa web cũng được cho vào đấy (đã xóa đi trong nhánh master). 
https://github.com/tdan/homepage

**Comment by icy** [comment]
@tdan: Mình cần tạm thêm cái `hook` trên kho git chính thức của dự án, và gửi cho @tdan quyền để `commit` thẳng vào đó . Sau mỗi `commit`, hệ thống sẽ chạy `nanoc` để tạo ra trang `staging`. 

Stay tuned!

**Comment by icy** [comment]
Chưa thể cung cấp môi trường `staging` một cách an toàn được.
