### ISSUE TITLE
Tạo package mirror cho ArchLinux (và TheSLinux)

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#113]
## Mục đích

Tạo mirror của các gói cho ArchLinux, TheSLinux (future)
## Các bước thực hiện
1. Cài một máy ảo VirtualBox Debian 7 (squeeze), 64 bit, với thông tin sau
   - tên máy: phant6m8.theslinux.org
   - kích thước đĩa: 100GB (.vdi, dynamic size)
   - khi cài đặt, sử dụng cách phân vùng riêng (/usr/, /var, /tmp, /home/, ...) theo đề nghị của trình cài đặt Debian;
   - ip tĩnh: 10.6.8.15 (lớp mạng /24, gateway 10.6.8.2)
   - thiết lập NAT trên VirtualBox để kết nối ssh
   - sau khi cài xong, thiết lập đăng nhập qua `ssh` cho một account bất kỳ, với đầy đủ quyền `sudo`; sử dụng `ssh` key cá nhân cùng với key của @icy ở https://github.com/icy.keys
   - tắt máy ảo `phant6m8` và tải lên máy `phant6m`
2. nếu cần thiết, ghi lại các chú ý quan trọng khi cài đặt để sau này còn sử dụng
3. Làm việc với @icy để kết nối máy mới vào trong hệ `puppet` của dự án
4. Cài đặt phiên bản `custom` của `nginx`
5. Làm việc với trung tâm dữ liệu Đà Nẵng (DSP), để lấy thêm IP tĩnh và băng thông
6. Chuẩn bị kịch bản để tạo mirror cho `ArchLinux`. Liên hệ @icy để có kịch bản cũ đã dùng trước đây
7. Thử nghiệm và thông báo trên các kênh (nhóm thư, facebook, twitter)

**Comment by icy** [comment]
Cách đăng nhập vào server mới: Thêm vào `~/.ssh/config` các dòng sau

```
Host phant6m
  Hostname PRIVATE_IP
  User USER_NAME
  Port PORT_NUMBER

Host phant6m8
  Hostname 127.0.0.1
  User USER_NAME
  Port 2268
  ProxyCommand ssh phant6m -W 127.0.0.1:2268 -fN
```

Sau đó dùng lệnh `ssh phant6m8` là xong.

**Comment by icy** [comment]
@xngqhy Tạm thời đã ổn, cái `nginx` để a coi sẽ làm tiếp thế nào. Do bộ cấu hình a đã vứt tùm lum chưa lấy lại được :D Có gì trong tuần tới làm tiếp. Cảm ơn em nhiều!

**Comment by icy** [comment]
Chuẩn bị có IP cho máy ảo :)

**Comment by icy** [comment]
Tình trạng hiện tại:
1. Đã có được ip tĩnh, và đã thiết lập mirror http://f.theslinux.org/
2. Đang chạy thử kịch bản tạo mirror (https://github.com/archlinuxvn/mirror-scripts)

@xngqhy : Khi nào kịch bản thử chạy xong, a sẽ điều chỉnh các thông tin cần thiết để e có thể làm việc. A thêm em vào nhóm ghi vào https://github.com/archlinuxvn/mirror-scripts, em có thể check-out về kiểm tra thế nào (có hai nhánh `master` và `stable` nhé.) Hiện tại em có thể đăng nhập vào máy `phant6m8`, và theo dõi kịch bản đang chạy hoặc các thông cơ bản, mặc dù em chưa có quyền ghi vào `/home/www/public/`.  Stay tuned!

TODO:
1. Thêm http://f.archlinuxvn.org/
2. Hỗ trợ backup
3. Theo dõi băng thông, bla bla

**Comment by luk4hn** [comment]
@icy: ok anh, em coi qua một vòng rồi, script mirror anh dự tính sẽ set cronjob hourly hay thế nào :)

P.S: cuối tuần t5-cn em đi teambuilding với cty nên sẽ offline nhé :smiley:

**Comment by icy** [comment]
@xngqhy Mình sẽ chạy khoảng 6 giờ một lần, lấy gói từ các tier-1 mirror của ArchLinux. 

Về thời gian thì cứ từ từ không vội đâu. :) Có nhiều vấn đề với kịch bản đó (locking, logging, bla bla). Có thời gian thì làm thêm phần theo dõi băng thông, số lượng người sử dụng, thêm phần mã nguồn, bla bla. Làm cũng sẽ biết được nhiều thứ hay :)

**Comment by icy** [comment]
Đã thêm CNAME record http://f.archlinuxvn.org/

**Comment by icy** [comment]
Tất cả các vấn đề :)
1. Backup cho cấu hình của phant6m8
2. Theo dõi băng thông, lượng người sử dụng
3. Cronjob cập nhật mirror từ tier-1, chuyển đổi qua lại giữa các tier-1 mirror
4. Tham khảo điều kiện sử dụng của các tierr-1 mirror
5. Locking cho kịch bản `sync.sh`
6. Tạo tài khoản riêng `mirror`
7. Điều chỉnh cache trên nginx, để xem liệt kê (index page) nhanh hơn
8. Mirror cho một số mã nguồn của ArchLinux (hỗ trợ cho TheSLinux)

**Comment by icy** [comment]
9 . Tạo trang index page cho đẹp, hướng dẫn cách sử dụng mirror và vài dòng lịch sử.

**Comment by icy** [comment]
10 . Tải về các tập tin iso :)

**Comment by icy** [comment]
Xong: 3; 5; 6

**Comment by icy** [comment]
11 . Tìm hiểu khả năng bổ sung thêm cho ArchARM, ManjaroLinux

**Comment by icy** [comment]
Mirror dành cho ArchLinuxArm gần hoàn thiện http://vn.mirror.archlinuxarm.org/status.json . 

Còn nhiều việc phải làm quá

12 . Kiểm tra xem cách cấu hình và điều chỉnh cấu hình mirror
13 . Tăng cường hệ thống backup và mirror backup (!?)
14 . Viết tài liệu hướng dẫn cơ bản (trang index.html) cho ArchLinuxARM
15 . Các vấn đề bảo mật, thông báo trạng thái, bla bla.

**Comment by icy** [comment]
16 .  Tạo mirror của kho git/svn của ArchLinux
