### ISSUE TITLE
hỗ trợ qt5 cho uim-vi

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#116]
Phiên bản hiện tại uim-vi chỉ hỗ trợ qt4. Để dùng qt5 cần trộn hoặc chọn ra thay đổi trên nhánh uim-vi để đặt vào nhánh `uim/master`. Lưu ý là `uim` chưa công bố phiên bản chính thức hỗ trợ `qt5`.

**Comment by icy** [comment]
Cảm ơn @NgoHuy đã qua được bước đầu tiên ngon lành. Tiếp theo nè
1. Viết tóm lại những thứ đã làm để khỏi quên. Public hay không cũng được nhưng không nên bỏ lên Facebook =)) Phần đầu tiên cần viết là mục tiêu của `uim-vi`
2. Nhánh stable hiện tại của `uim-vi` là `uim-vi-1.8` https://github.com/TheSLinux-forks/uim/commits/uim-vi-1.8 (ứng với các phiên bản `uim-vi-1.8.5`, `uim-vi-1.8.6`, ...) . A sẽ tạo ra nhánh `uim-vi-1.9` để cho ra các phiên bản `uim-vi-1.9.0`, `uim-vi-1.9.1`, bla bla và sẽ bắt đầu tái tạo lại các `cherry-pick` trênh nhánh này
3. Khi cherry-pick, điều quan trọng là nhớ để reference tới commit cũ ,để sau này tiện theo dõi. Nếu có xung đột thì giải quyết và ghi rõ trong commit body. Vi dụ về commit message như sau đây. E có thể dùng short hash (dùng full hash đọc hơi nhức mắt)

```
Subject: cp uim-vi-1.8 #1701a12a7: Remove :state icon on systray 

Thông tin giải quyết các xung đột có thể
```

Ở đây, `Remove :state icon on systray` là chủ đề cũ. Em có thể viết bằng tiếng Việt luôn cho tiện. Quan trọng là rõ nghĩa, không cần viết tiếng Anh tối nghĩa.
4. Anh sẽ review lại `pull request` và điều chỉnh nếu cần rồi `merge` vào nhánh chính `uim-vi-1.9`

Cảm ơn em nhiều!

**Comment by icy** [comment]
`uim-vi-1.9` https://github.com/TheSLinux-forks/uim/tree/uim-vi-1.9 . Nhánh này giờ giống hệ `master` của `uim`

**Comment by icy** [comment]
@NgoHuy A thấy pull request rồi. Hơi bờm cái để  #1701a12a thì không có link ,  1701a12a thì sẽ có :) Thôi không sao hôm nay a sẽ coi và merge vào nhánh chính.

**Comment by NgoHuy** [comment]
há, giờ em mới biết có vụ này =))

**Comment by icy** [comment]
Xem thêm #130
