### ISSUE TITLE
Thêm Huy vào nhóm quản lý mirror

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#122]
https://github.com/archlinuxvn/gs/issues/3
- shel access
- email support
- notification support

shell access => done

**Comment by icy** [comment]
Việc đang làm là tách các mirror ra từng account để tiện quản lý, không ảnh hưởng qua lại lẫn nhau.

**Comment by icy** [comment]
- archlinux: account `archlinux`
- archlinuxarm: account `archlinuxarm`

**Comment by icy** [comment]
@NgoHuy đã có account đăng nhập vào `phant6m8`, sử dụng port forwarding như trước đây e đã biết, nhưng với port `2268`.

@NgoHuy và @xngqhy : giờ hai bạn có quyền quản lý mirror như nhau. Sau khi đăng nhập thì sử dụng `sudo` để chuyển đến từng account riêng. Tuy cùng kịch bản nhưng do locking mà mỗi account chỉ có thể cập nhật đúng một kho thôi. Xem commit https://github.com/archlinuxvn/mirror-scripts/commit/553826edccf1bf1253d94e1f57d7a569b73187e4

Tạm thời, @NgoHuy đăng nhập vào vào tìm hiểu các kịch bản, logging, **không làm bất cứ thứ gì rồ dại** nhé. Ưu tiên cho @NgoHuy làm việc trên #123. Trong việc giao tiếp chính thức với đội phát triển ArchLinux (ARM), bạn @xngqhy sẽ đảm nhận.

Có bất cứ vấn đề gì, các bạn liên hệ qua kênh irc, skype, hoặc nhóm thư chung f@archlinuxvn.org . 

Cảm ơn các bạn.

**Comment by icy** [comment]
@xngqhy Với mirror dành cho ArchLinux, a đã tắt bớt một số tier-1 server vì nó quá chậm.

**Comment by NgoHuy** [comment]
`Không làm bất cứ thứ gì rồ dại`, ="= em sẽ làm việc trên #123
