### ISSUE TITLE
LUKS bootstrap script

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#13]
Write a script to create LUKS partition in the first boot

**Comment by NgoHuy** [comment]
I wrote it on I created live usb.
https://github.com/NgoHuy/My-Project-/blob/master/parted

**Comment by icy** [comment]
Một bài đáng đọc http://www.debian-administration.org/article/692/Look_before_you_leap_into_Disk_Encryption

**Comment by icy** [comment]
1. Sẽ không mã hóa toàn bộ các phân vùng `/`
2. Chỉ mã hóa phân vùng dữ liệu, không mã hóa phân vùng `/home/` hay `/home/<user>/`
3. Sẽ sử dụng `truecrypt`  hoặc `ecryptfs` với giao diện đồ họa sẵn có 
4. Không sử dụng `luks` (mặc dù tính năng `resize` của `luks` rất hay) vì thiếu giao diện đồ họa. Nếu có giao diện thân thiện thì có thể xem xét dùng, như 3.)

**Comment by icy** [comment]
Một bài so sánh giữa `truecrypt` và `luks`, mặc dù không có gì đặc biệt https://bbs.archlinux.org/viewtopic.php?id=85694&p=2

**Comment by icy** [comment]
Sẽ không hỗ trợ kịp trong dòng G1 sắp tới.
