### ISSUE TITLE
uim-vi-1.9: review, kiểm tra và đóng gói

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#130]
- Review các thay đổi @NgoHuy thực hiện trên https://github.com/TheSLinux-forks/uim/pull/1
- Kiểm tra các tính năng cơ bản
- Kiểm tra nếu có vấn đề với ứng dụng cũ (chuẩn bị tài liệu)
- Kiểm tra cho các ứng dụng qt5
- Đóng gói để sử dụng lâu dài

**Comment by icy** [comment]
Khi biên dịch thì gặp lỗi, đúng chỗ mà @NgoHuy đã vá. Câu hỏi
1. Thư mục `/usr/plugins`/ lạ quá, có đúng cho `qt5` không?
2. Miếng vá của @NgoHuy (https://github.com/TheSLinux-forks/uim/pull/2) không hỗ trợ `prefix` được chỉ ra lúc chạy `sh configure` và / hoặc hỗ trợ `fakeroot`?

```
s/theslinux/buildsystem/uim-vi/src/uim-uim-vi-1.9/uim ....
mkdir: cannot create directory ‘/usr/plugins’: Permission denied
Makefile.qmake:118: recipe for target '/usr/plugins/platforminputcontexts/libuimplatforminputcontextplugin.so' failed
make[3]: *** [/usr/plugins/platforminputcontexts/libuimplatforminputcontextplugin.so] Error 1
make[3]: Leaving directory '/home/pi/projects/theslinux/buildsystem/uim-vi/src/uim-uim-vi-1.9/qt5/immodule'
Makefile:595: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/pi/projects/theslinux/buildsystem/uim-vi/src/uim-uim-vi-1.9/qt5/immodule'
Makefile:507: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/projects/theslinux/buildsystem/uim-vi/src/uim-uim-vi-1.9/qt5'
Makefile:639: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by NgoHuy** [comment]
@icy anh đã patch đâu, anh có thể xem PKGBUILD của em
https://github.com/NgoHuy/uim/blob/uim-vi-1.9-PKGBUILD/pkgbuild/PKGBUILD

**Comment by icy** [comment]
https://github.com/uim/uim/pull/49
https://github.com/uim/uim/pull/50

Khi build với bản qt5, quá nhiều debug/ message do `qDebug()` in ra làm chậm hệ thống.

**Comment by icy** [comment]
Xem https://github.com/TheSLinux/buildsystem/commit/0d677155d54e0d37060dd26e59b56fa690bf5ae3
