### ISSUE TITLE
linux zine!

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#131]
cc: @dynamotn

Các ý tưởng để tạo một chỗ chung tóm tắt các tin vắn liên quan tới Linux trong tuần (tháng).

**Comment by dynamotn** [comment]
Có lẽ đầu tiền phải lên list rss/news để qua đó dịch trước anh ạ

**Comment by icy** [comment]
Vài gợi ý
1. http://lwn.net/ (có thể chung tiền mua tài khoản luôn; $10/tháng; nhưng phải coi chừng giấy phép.)
2. Weekly topics trên Hacker News (có liên quan Linux và oss). Cái này nhiều. Nên bạn nào đọc thấy cái nào hay thì note chung lại cho mọi người tham khảo / biết sau này có khi cần.
3. Một số chủ đề khác
