### ISSUE TITLE
e17-svn build script

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#14]
*Write script to build e17 from svn

**Comment by icy** [comment]
See also http://archlinuxvn.org/s/icy/e17/build.script (this script is very out-of-date)

**Comment by NgoHuy** [comment]
e17 đã chuyển từ svn sang git. Hiện em đang build từ git, không hiểu sao bản svn không tìm thấy các gói cần thiết trong repo nữa.
- Svn: http://trac.enlightenment.org/e/browser/trunk?order=date
- Git: http://git.enlightenment.org/

Hiện tại cấu trúc git thay đổi khá nhiều bởi việc gom các thư viện làm một chuẩn bị chi e18.

**Comment by icy** [comment]
On Wed, 13 Mar 2013 07:42:44 -0700
Ngô Huy notifications@github.com wrote:

> e17 đã chuyển từ svn sang git. Hiện em ddnag build từ git, không hiểu
> sao bản svn không tìm thấy các gói cần thiết trong repo nữa.
> - Svn: http://trac.enlightenment.org/e/browser/trunk?order=date
> - Git: http://git.enlightenment.org/
> 
> Hiện tại cấu trúc git thay đổi khá nhiều bởi việc gom các thư viện
> làm một chuẩn bị chi e18.

Em coi tài liệu dành cho Developer của e17 nhé. Nếu chưa đúng thì lên
#e17 hỏi thêm.

## 

I am ... 5 dog years old.

**Comment by NgoHuy** [comment]
Em đã hoàn tất việc build e17 trên git với 5 gói thư viện chính bao gồm: EFL, Elementary, Enlightenment, evas_generic_loaders và emotion_generic_loaders. Buildscripts có thể xem tại link sau, có hướng dẫn : 
- https://github.com/NgoHuy/buildsystem/tree/e17/e17

**Comment by icy** [comment]
Tạo pull request  giúp anh. Thanks

**Comment by NgoHuy** [comment]
anh tạo một nhánh là e17 hộ em với em tạo pull request qua ah

**Comment by icy** [comment]
ok để a coi

**Comment by icy** [comment]
Huy ơi em có biết e17 có sắp ra phiên bản nào mới không!?

**Comment by NgoHuy** [comment]
e17 hiện đang là 0.17.2. Trên git hiện là bản 0.17.99 chuẩn bị cho bản 0.18 vào cuối năm anh ah

**Comment by icy** [comment]
Theo anh biết, viện biên dịch bộ `e17` khá phức tạp, thể hiện ít nhất ở các điểm sau

1/ Phải biên dịch các thư viện đi kèm
2/ Phải biên dịch đúng thứ tự các thư viện (em xem kịch bản mà anh gửi ở trên)

Ngoài ra, nếu em gộp chung các `PKGBUILD-*` vào một gói thế này cũng là ý hay, nhưng a thấy vẫn chưa đủ tất cả các thư viện đi kèm của `e17`.

**Comment by icy** [comment]
A đã `push` lên nhánh `enlightenment17` gần nguyên từ `PKGBUILD` của ArchLinux, có điều chỉnh tí ti thôi. Em có thể chỉnh lại

**Comment by NgoHuy** [comment]
Đoạn kịch bản của em là em build từ git, đã sắp xếp thứ tự thư viện.  Bản 0.17.99 thư viện đã gom khá nhiều lại vơi nhau, thực chất là build 5 gói core trong 1 đoạn kịch bản từ 5 bản PKGBUILD (trong đó có enlightenment17). 
Anh có thể xem thêm ở đây
http://git.enlightenment.org/

**Comment by icy** [comment]
Các gói nên tách nhỏ ra, vì sẽ dễ maintain hơn là gộp chung lại. Ví dụ chỉ chỉ có thay đổi nhỏ trong một phần của thư viện, không phải biên dịch _(và đánh số phiên bản)_ cho trọn bộ. Cái gì ra cái đó.

**Comment by NgoHuy** [comment]
ah, em hiểu nhầm ý của anh bảo thiếu thư viện không biên dịch được  :D

**Comment by icy** [comment]
Huy coi tách ra các gói nhỏ nhé. Nếu cần tạo ra các gói mới thì em có thể bắt đầu từ nhánh `TheBigBang` hoặc `TheSmallBang`. Có thể nói a tạo ra các nhánh trước. Có thể đặt tên `e17-foobar` cho gọn. Nếu không dùng nhánh `enlightenment17` thì nói anh đặt cờ bỏ qua nhánh này.

**Comment by icy** [comment]
Để ý trong `enligtenment17` có miếng vá dành riêng cho `systemd`.

**Comment by NgoHuy** [comment]
Dùng để thay poweroff của  gói sysvinit đó anh :P

2013/5/12 Ky-Anh Huynh notifications@github.com

> Để ý trong enligtenment17 có miếng vá dành riêng cho systemd.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TheSLinux/gs/issues/14#issuecomment-17773799
> .

## 

'_Tình yêu là sự cố gắng của một người để *_chỉ yêu thương một người mà thô*
i.'

**Comment by icy** [comment]
Vấn đề là em phải thể hiện cái đó trong kịch bản `build` của em, còn nó làm gì thì a cũng có thể đọc được .

**Comment by NgoHuy** [comment]
Em đã tạo pull request.

**Comment by icy** [comment]
Bữa sau nhớ link vào luôn cho dễ tìm Huy nhé.

https://github.com/TheSLinux/buildsystem/pull/3

**Comment by icy** [comment]
Đóng chủ đề này lại. Các vấn đề khác hãy trao đổi trên hệ thống `buildystem` như link vừa nêu ra ở trên.
