### ISSUE TITLE
auto-mount support

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#15]
Find a good tool (GUI is welcome) to mount all knơwn partitions on the system

**Comment by NgoHuy** [comment]
file manager such as nautilus can do it

**Comment by icy** [comment]
On Tue, 12 Mar 2013 07:26:17 -0700
Ngô Huy notifications@github.com wrote:

> file manager such as nautilus can do it

có phải bê nguyên gnome vào không em? auto-mount thì không cần mấy cái
to đùng thế đâu em, chưa kể cách cấu hình của nautilus khó mà theo ý
của em được.

check lại giúp a nhé.

## 

I am ... 5 dog years old.

**Comment by NgoHuy** [comment]
không phải bê nguyên Gnome đâu anh.
Em nhận xét thấy cũng cần file manager tiện dùng hơn file managfer mặc định của E17. Ngoài nautilus, ta còn có Thunar nhẹ hơn, nhanh hơn nautilus.

**Comment by icy** [comment]
On Tue, 12 Mar 2013 08:31:41 -0700
Ngô Huy notifications@github.com wrote:

> không phải bê nguyên Gnome đâu anh.
> Em nhận xét thấy cũng cần file manager tiện dùng hơn file managfer
> mặc định của E17. Ngoài nautilus, ta còn có Thunar nhẹ hơn, nhanh hơn
> nautilus. 

Cái nào ra cái đó em. Auto-mount chỉ cần một lần, khi khởi động bật máy
lên thì tát cả các phân vùng trên máy sẽ tự động kết nói vào. (Nếu có
gắn thêm USB khác vào thì hehe mình tính chuyện khác !?) Việc này không
cần làm qua Nautilus hay Thunar. Có thể viết một daemon hoặc một
cron-based job để tự kết nối các đĩa trên máy. 

Không rõ các huớng giải quyết trên các hệ thống đã có như thế nào.

**Comment by NgoHuy** [comment]
Các hướng giải quyết thì có udev rules, ta viết một file udev chỉ định khi các usb/removal devices được gắn kết thì sẽ thực hiện một hành động/script nào đó. Một hướng khác là cài udisks. Tuy nhiên udisks có vẻ không hiệu quả bằng udev rules khi auto mounts.

**Comment by icy** [comment]
On Thu, 14 Mar 2013 04:48:48 -0700
Ngô Huy notifications@github.com wrote:

> Các hướng giải quyết thì có udev rules, ta viết một file udev chỉ
> định khi các usb/media được gắn kết thì sẽ thực hiện một hành
> ddoongj/script nào đó. Một hướng khác là cài udisks. Tuy nhiên udisks
> có vẻ không hiệu quả bằng udev rules khi auto mounts.

Cần phân biệt 2 bài tóan khác nhau nhé. Các ổ cứng trên máy tính thì
không cần un-mount, Các ổ USB gắn thêm, thì sẽ phải có hỗ trợ để người
dùng unmount trước khi rút đĩa ra. Cái này hơi phức tạp :D 

## 

I am ... 5 dog years old.

**Comment by thuandt** [comment]
@NgoHuy dùng udev rules là một hướng hơi dở. Hardcore mà chưa chắc đã hiểu quả bằng việc sử dụng udisk và viết rules mount cho policykit
@icy em vote dùng udisk. Automount khi người dùng cắm USB hoặc HDD vào là cần thiết. Udisk nó support việc này. Chuyện umount bằng Nautilus, Thunar hay Filemanager là chuyện của filemanager.

**Comment by NgoHuy** [comment]
udisks được yêu cầu bởi gói e17, vấn đề filemanager muốn mount/umount phải thông qua polkit để xác thực và udisks hoặc một gói tương tự để tiến hành, việc dùng filemanager sẽ dễ dàng hơn cho việc phát triển mà không cần quan tâm bên dưới, tất nhiên viết rules cho udisk em đã thử, mặc định người dùng nhóm storage có quyền mount/umount các thiết bị ngoại vi. 
Với yêu cầu chạy trên usb thì xem như ổ cứng của máy là thiết bị ngoại vi, nó cũng cần được mount anh ah, umount như bình thường ( ý của anh có phải là umount là việc nó làm khi shutdown và cũng không tháo ra nên không quan tâm :-D)
Cảm ơn ý kiến của anh :-)

**Comment by thuandt** [comment]
Everything is done?

**Comment by icy** [comment]
Mình nghĩa là chưa. Do @NgoHuy lâu ngày không cập nhật `status` nên chưa rõ tiến độ thế nào :)

@NgoHuy "Cảm ơn anh đã cho ý kiến" viết cho đúng nhé :D
