### ISSUE TITLE
uim-vi: critical problem with Firefox > 34

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#151]
The current `uim-vi` (1.9) can cause Firefox > 34 to crash.

Please take a look and find the cause. The first thing is to test if a similar problem occur with `uim-vi-1.8.7`

**Comment by NgoHuy** [comment]
When I test uim-vi-1.8.7, problem occured again, but I found that it only occured when I use XTELEX, not m17n-vi-telex, the both uim-vi-1.8.7 and uim-vi@qt5 are affected

**Comment by icy** [comment]
Trên Firefox 36: Khi vào nhóm Facebook của #archlinuxvn gửi bài thì bình thường. Tuy nhiên, khi bình luận thì treo (chỉ cần chuột di chuyển ngang khung bình luận cũng treo; `segmentation fault`). 

Trên Github thì gửi bình luận bình thường đây.

Nhớ (!?) hồi xưa lên firefox 35 thì bị treo kịch liệt hơn nhiều!

**Comment by icy** [comment]
Rồi thêm một cái comment trên Facebook ngon lành. Không hiểu sao. Trước đó thì crash.

Xem: https://www.facebook.com/groups/archlinuxvn/permalink/333382796855449/

**Comment by icy** [comment]
Có thể tái hiện lỗi như sau đây: dùng kiểu gõ `xtelex`, đang ở khung bình luận của `facebook`, gõ vào `aa` (như vậy, sẽ đang ở chế độ chờ để hoàn tất), rồi di chuyển chuột (hoặc không cần!), thì trình duyệt sẽ bị treo ngay.

**Comment by icy** [comment]
Fixed in https://github.com/TheSLinux-forks/uim/commit/ff2dbcdb40098338d55408dd96c0bf677eedfe8b . 

I'm going to build new packages for new testing....

**Comment by icy** [comment]
Gói mới sẵn sàng để Huy test nhé : uim-vi@qt5-nocandwin-git-ff2dbcd-1.9-2-x86_64 (đã có trên `repo` của `theslinux`.)

**Comment by icy** [comment]
@NgoHuy also tested with `midori-gtk3`, and the crash doesn't happen. However, I believe the same issue may happen in the future. We still keep this stable for now.

We don't cherry-pick the last commits to fix the similar issues on `uim-vi-1.8`. We will soon mark it _unsupported_.
