### ISSUE TITLE
Booting fail with 2 partitions on usb

### ISSUE THREAD

**Issue by NgoHuy** [TheSLinux/gs#16]
Khi dùng dd + fdisk, việc phân vùng diễn ra đúng như mong muốn, tuy nhiên khi boot lên thì hầu hết thất bại do nhận sai phân vùng boot sang phân vùng mới tạo.
- Đề nghị giải quyết: thêm tham số vào kernel boot chỉ rõ phân vùng boot

**Comment by icy** [comment]
On Thu, 14 Mar 2013 02:53:22 -0700
Ngô Huy notifications@github.com wrote:

> Khi dùng dd + fdisk, việc phân vùng diễn ra đúng như mong muốn, tuy
> nhiên khi boot lên thì hầu hết thất bại do nhận sai phân vùng boot
> sang phân vùng mới tạo.
> - Đề nghị giải quyết: thêm tham số vào kernel boot chỉ rõ phân vùng
>   boot

Tham số này là là thế nào? Ai thêm vào? Huy cho thêm ví dụ cho rõ nhé.
Thanks

**Comment by NgoHuy** [comment]
Là mình tự thêm vào khi chỉnh sửa syslinux.cfg. Thay vì tham số archisolabel ( tự gắn symlink tới phân vùng có 
nhãn đó) thì thêm tham số archisodevice=/dev/sdbX  để chỉ rõ root nằm ở phân vùng nào (hoặc earlymodules=loop). Vì khi boot đôi khi việc gắn nhãn bị sai (em đang tìm hiểu vì sao gắn sai)
- Boot process: https://wiki.archlinux.org/index.php/Arch_Boot_Process
- Mkinitcpio: https://wiki.archlinux.org/index.php/Mkinitcpio

**Comment by icy** [comment]
On Thu, 14 Mar 2013 04:56:10 -0700
Ngô Huy notifications@github.com wrote:

> Là mình tự thêm vào khi chỉnh sửa syslinux.cfg. Thay vì tham số
> archisolabel ( tự gắn symlink tới phân vùng có nhãn đó) thì thêm tham
> số archisodevice=/dev/sdbX  để chỉ rõ root nằm ở phân vùng nào (hoặc
> earlymodules=loop). Vì khi boot đôi khi việc gắn nhãn bị sai (em đang
> tìm hiểu vì sao gắn sai)
> - Boot process: https://wiki.archlinux.org/index.php/Arch_Boot_Process
> - Mkinitcpio: https://wiki.archlinux.org/index.php/Mkinitcpio

Em coi cách làm của các liveCD/USB. Nếu mình phải gán thêm cái tham số
cho kernel lúc khởi động thì coi như vứt, chả ma nào xài.

## 

I am ... 5 dog years old.

**Comment by NgoHuy** [comment]
Từ từ detect lỗi đã anh, bước phân vùng coi như tạm ổn :dancers:

**Comment by NgoHuy** [comment]
Done ! cần tạo label cho phân vùng data để tránh mount nhầm vùng data, boot tốt.
