### ISSUE TITLE
m17n custom + fix

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#17]
- điều chỉnh để thu gọn gói m17n
- chỉnh các gõ tắt phiền toaí

**Comment by icy** [comment]
Trong m17n thì chữ w gõ thành ư , nên khi tõ chữ swap thì rất ư là khó chịu. Việc gõ tắt như vậy khong cần thiết. Chỉ cần cung cấp bảng gõ theo đúng kiểu telex đơn giản nhất. Những vấn đề khác sẽ được xử lý theo cách khác.

**Comment by NgoHuy** [comment]
Đã nhận và sẽ xử lý.

**Comment by NgoHuy** [comment]
Solution:
- comment dòng 61-62 file vi-telex.mim.
- Chọn ngôn ngữ gõ chỉnh sửa makefile để chọn thay vì tất cả.

**Comment by icy** [comment]
> comment dòng 61-62 file vi-telex.mim.
> Chọn ngôn ngữ gõ chỉnh sửa makefile để chọn thay vì tất cả.

Nếu dùng PKGBUILD riêng thì em bỏ lên REPOs nhé không cần report lại
đây. Nếu ok em có thể tự đóng ticket ^^

## 

I am ... 5 dog years old.

**Comment by icy** [comment]
@Huy: Cần làm miếng vá chứ không chỉnh bằng tay nhé Huy. Anh nghĩ là chỉnh trong `Makefile.in` chứ không hải là `Makefile` đâu. Có gì cho biết nếu gặp khó khăn.

**Comment by NgoHuy** [comment]
@icy  em làm miếng vá mà, file makefile.am và cả .in nữa hai file này generate ra file Makefile.

**Comment by icy** [comment]
Việc đổi chữ `w` này cũng chỉ khắc phục được một số trở ngại thôi, còn lại vẫn phải đau đầu với `tow`. Nếu gõ bằng `telex` thì a không rõ làm thế nào để gõ nhanh từ đó cả.

**Comment by icy** [comment]
Chuyển qua dòng 2 vì cần tìm hiểu kỹ hơn về các kiểu gõ tiếng Việt cũng như các hỗ trợ hiện có trong #uim-vi

**Comment by icy** [comment]
Thư viện `m17n-db` được thu gọn lại trong gói `m17n-db-vi`. Hiện tạicác hỗ trợ so với định nghĩa gốc (https://vi.wikipedia.org/wiki/VNI) bị loại bỏ; bao gồm
1. Các định nghĩa sử dụng chữ **w** thay cho **ư** trong kiểu gõ Telex
2. Các định nghĩa dùng số **7** thay cho chữ **ư** trong kiểu gõ VNI

Chủ đề này được đóng lại. Nếu có vấn đề phát sinh khác vui lòng mở ticket mới.
