### ISSUE TITLE
Performance test

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#18]
- Kiểm tra tốc độ đọc , ghi của USB (có LUKS)
- Kiểm tra tốc độ làm việc của firefox / office tool

**Comment by NgoHuy** [comment]
Đã nhận, Luks đang tiến hành, Firefox/Office sẽ có bản record trong tuần tới.

**Comment by icy** [comment]
Huy lưu trữ các số liệu kiểm tra, ghi rõ cách thực hiện các kiểm tra, khi cần sẽ dùng vào các bài trình diễn hoặc có thể tiến hành kiểm tra lại nhé. Tạm thời chỉ đánh giá sơ bộ về khả năng .
