### ISSUE TITLE
m17n clean up

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#19]
Thư viện `m17n` có quá nhiều ngôn ngữ không cần thiết. Tạo một gói con để ví dụ `m17n-data-vi` chỉ gồm các ngôn ngữ hay dùng, ví dụ tiếng Việt, tiếng ANh (en_US, en_UK)

**Comment by icy** [comment]
Sau phần clean up sẽ chỉnh một số vấn đề của m17n, xem trong #17

**Comment by icy** [comment]
Tên gói `m17n-data-vi`. Có cả `m17n-lib` nhưng anh không rõ có phải dùng tới nó không.

**Comment by NgoHuy** [comment]
Có anh, nó là "Multilingual text processing library (runtimes)".
m17n-lib lấy m17n-db để xác định ngôn ngữ, m17n-lib có mặc định anthy và libthai, có bản vá để loại bỏ anthy và libthai

**Comment by NgoHuy** [comment]
Em đã viết patch tại đây: http://severus.no-ip.org:8080/Archlinux/m17n-vi/
Hiện tại còn Font layout của m17n-db em giữ nguyên các loại font không phải tiếng Việt và keymap.

**Comment by icy** [comment]
Khkông vào đựoc em ơi. Trang web rớt lên rớt xuống thế thì đừng bỏ lên đây nhé.

A đã làm trong repo `theslinux-buildsystem` rồi, em có thể kiểm tra trong nhánh `m17n-db-vi`. Em muốn chỉnh gì thì fork về tạo nhánh riêng dựa trên nhánh đó rồi tạo miếng vá rồi gửi email cho anh (Tạm thời là vậy) hoặc gửi vào ticket này.

**Comment by NgoHuy** [comment]
Em xin lỗi, em đã tắt server luôn rồi. Em sẽ fork repo rồi commit vào
Hiện đây là patch và PKGBUILD mới
http://www.mediafire.com/?96ub16duff2kut2

**Comment by icy** [comment]
Em `clone` về rồi tạo nhánh riêng

```
git checkout m17n-vn-vi
git checkout -b m17-vn-vi-huy-foobar
# em thay huy-foobar với tên tính năng gì đó
# thay đổi, commit
# tạo miếng vá
git format-patch m17n-vn-vi --stdout > foobar.patch
```

Google thêm về `git` nhé.

**Comment by icy** [comment]
Em không có quyền ghi vào `repo` chính nên phải thông qua miếng vá. Khi nào a `push` kho lên `github` thì sẽ tạo `pull request` dễ dàng hơn.

**Comment by NgoHuy** [comment]
Ok anh, em đã nhận. Các gói khác em cũng sẽ xem và viết patch nếu cần gửi anh sau.

**Comment by icy** [comment]
Hầu hết các gói khác a `import` đều đã chỉnh sơ em có thể dùng ngay. Cái nào cần chỉnh sẽ có ticket ở trên này truớc để khỏi làm lung tung dẫm chân nhau. Em cần làm gì cũng để `ticket` trên này trước để a theo dõi.

**Comment by icy** [comment]
Khi `pull` về em nhớ dùng `rebase`. Chạy lệnh `git pull --rebase`

**Comment by NgoHuy** [comment]
em có quyền commit vào repo đâu anh sợ em làm bậy :D. Với lại, muốn thay đổi thì em sẽ luôn tạo issue phân tích trước mà :-)

**Comment by icy** [comment]
On Fri, 05 Apr 2013 08:08:45 -0700
Ngô Huy notifications@github.com wrote:

> em có quyền commit vào repo đâu anh sợ em làm bậy :D. Với lại, muốn
> thay đổi thì em sẽ luôn tạo issue phân tích trước mà :-) 

không sợ e `commit` lên nhưng nếu dùng không đúng quen tật khó chữa.

## 

I am ... 5 dog years old.

**Comment by NgoHuy** [comment]
éc :+1:

**Comment by icy** [comment]
On Fri, 05 Apr 2013 08:19:10 -0700
Ngô Huy notifications@github.com wrote:

> éc :+1: 

Bớt `éc` đi em . Tốn điện nóng trái đất quá :))

## 

I am ... 5 dog years old.
