### ISSUE TITLE
[UEFI] Efi ia32 hung on boot in virtualbox

### ISSUE THREAD

**Issue by NgoHuy** [TheSLinux/gs#2]
I built iso file successfully, it works fine with x64 system but hangs on i686 virtual machine.

**Comment by NgoHuy** [comment]
I built gummiboot on i686 machine. It boots fine. Done make iso image !

**Comment by icy** [comment]
UEFI  ssẽ là một `experimental feature`. Anh muốn chắc là kiểu boot
bình thường sẽ không ảnh hưởng gì và `stable` ngay cả khi có thể có
kiểu `UEFI`. Mình sẽ thiên về `syslinux` (có thể dùng bản beta của nó)
hơn là `grub2`.

Huy chuẩn bị các tài liệu kỹ thuật và yêu cầu phân vùng,...; A sẽ có
repo riêng để e gửi tài liệu tạm thời Huy cứ chuẩn bị tài liệu và giữ ở
máy cá nhân (nhớ backup:D). Có thể viết theo kiểu `nanoc`

**Comment by NgoHuy** [comment]
UEFI chỉ hỗ trợ đúng kiến trúc của nó, tức là nếu máy là 64bit thì chỉ chạy được UEFI file 64bit không thể chạy được 32 nữa. Nếu chỉ hỗ trợ i686 thì tạm thời chỉ hỗ trợ UEFI cho i686 (nhưng phần lớn UEFI mới đều là 64bit- xu thế từ bỏ dần 32bit).

**Comment by icy** [comment]
On Tue, 05 Mar 2013 22:27:49 -0800
Ngô Huy notifications@github.com wrote:

> UEFI chỉ hỗ trợ đúng kiến trúc của nó, tức là nếu máy là 64bit thì
> chỉ chạy được UEFI file 64bit không thể chạy được 32 nữa. Nếu chỉ hỗ
> trợ i686 thì tạm thời chỉ hỗ trợ UEFI cho i686 (nhưng phần lớn UEFI
> mới đều là 64bit- xu thế từ bỏ dần 32bit).

Bộ cài 32 bít vẫn có thể cài đựoc trên máy 64 bit, trong khi ngược lại
thì không. Do đó tạm thời chưa tính tới bản 64 bít. Nếu gặp trục trặc
với UEFI thì tạm thời bỏ UEFI qua một bên.
