### ISSUE TITLE
Thử nghiệm Google Authenticator

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#20]
http://code.google.com/p/google-authenticator/wiki/PamModuleInstructions

**Comment by NgoHuy** [comment]
cách đây 1 năm, em cũng tí tởn với nó và giờ là nghiêm túc với nó :-D

**Comment by icy** [comment]
Cái này làm cho biết khi cần áp dụng . Chắc không đi với LUKS được nhé Huy.

**Comment by NgoHuy** [comment]
Em lâu lâu nghĩ vào thứ vở vẩn thôi anh, không đi với Luks được :-D

**Comment by icy** [comment]
Dời qua #G2 vì cần kiểm tra kỹ các điểm hay - dở của tính năng này.

**Comment by thuandt** [comment]
Thật ra thì mục đích của việc này là gì hả @NgoHuy ?

**Comment by NgoHuy** [comment]
Để thử vài tính năng mà em nghĩ là sẽ cần lúc nào đó ;)

**Comment by thuandt** [comment]
Những tính năng nào, chia sẻ được không ?
Google Authenticator anh thấy áp dụng cho xác thực WebApp, hay xác thực từ mạng vào thì ổn hơn.

**Comment by icy** [comment]
Dùng để tạo `password` sinh một lần cho để đăng nhập và `ssh` server được đó @mrtuxhdb . Vấn đề mình băn khăn là cơ chế này vẫn có một số hạn chế nhất định. @NgoHuy  đã nghịch có thể chia sẻ thêm. Phần tích hợp với `LUKS` thì không thể rồi.

**Comment by thuandt** [comment]
@icy Nếu dùng **password** đơn thuần thì mặc định cái **pam module** của **google authenticator** nó support rồi. Vấn đề này thì em đã nghiên cứu khá kĩ. Khả thi và đã có nhiều người làm rồi.

Mặc định **pam module** nó chỉ support 2-step khi xác thực bằng password, còn khi xác thực bằng **public key** thì vẫn không cần mã HTOP. Tất nhiên, việc bắt người dùng xác thực bằng public key vẫn phải nhập mã HTOP là hoàn toàn làm được [ https://calomel.org/openssh_gatekeeper.html ]

Nói chung là modify cái script kia thì có thể thực hiện rất nhiều công việc mà mình muốn được.

**Comment by icy** [comment]
Thông tin @mrtuxhdb  rất bổ ích. Cái ý tưởng liên quan tới `Google` chỉ bất chợt nảy ra, tạm để đây khi nào cần sẽ dùng. Hy vọng là đồ của `Google` rất có ích trong tương lai. Ví dụ trong một số hệ thống bắt buộc phải dùng `password authentication` thì việc sinh ra `password` rất thích hợp với những người dùng **chẳng bao giờ nhớ được password** (ví dụ ... thầy hiệu trưởng của mình :D)

**Comment by icy** [comment]
Một bài hay về các điều hạn chế của Google Authenticator http://blog.mricon.com/2012/12/limitations-of-google-authenticator-pam.html . Đã tw. ở https://twitter.com/kyanh/status/316841540070821888

**Comment by icy** [comment]
=> rejected.
