### ISSUE TITLE
Find the best mailing list provider

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#21]
Description: We need to use some mailing list for the project. Google is the first option but there are some other options (yahoo, nabble, freelists.org). Please take a look and suggest the best service for our mailing lists. 

Expectation:
- free list
- no avertising
- there is a way to manage users (ban, block, add, remove)
- (optional) can support  our own domain (foobar@theslinux.org)

**Comment by xiongchiamiov** [comment]
You may also consider [Librelist](http://librelist.com/) - I haven't used it myself, but it's a very simple hosted list solution run by Zed Shaw.

**Comment by icy** [comment]
On Sat, 06 Apr 2013 11:07:24 -0700
James Pearson notifications@github.com wrote:

> You may also consider [Librelist](http://librelist.com/) - I haven't
> used it myself, but it's a very simple hosted list solution run by
> Zed Shaw.

Cool :) That really helps I will take a look.

Fyi, my first try was to use Nabble (simple and elegant). Unfortunately
it requires us to pay to remove banner(s). Payment is acceptable, but
Nabble doesn't support SSL and has quite unclear description in the
homepage (Actually I though I was trapped)

## 

I am ... 5 dog years old.

**Comment by icy** [comment]
- google group: advertising in main page, no downloadable archive, bad support (real experience)
- yahoo group:advertising
- librelist:good, using the very new mail server http://lamsonproject.org/
- freelists.org: stable, no adv., using Ecartis http://www.freelists.org/about.html

**Comment by icy** [comment]
I'd really like the name `theslinux-questions` but `librelist` doesn't allow that name ;)

```
Hi,

Sorry to tell you, but the list name you gave:

theslinux-questions@librelist.com

is not a valid name for a list at librelist.com.

You probably put a '-' character in it, but that character is used by
librelist to separate list names from commands.


WHAT IS VALID

List names can only have characters, numbers, and the '.' (period)
character.  You can't have any other special characters.


TRYING AGAIN

Simply just try again with a valid list name and we'll get to work on
making the list you want.


Thank you,
```

**Comment by icy** [comment]
`librelist.com` is simple and (so simple). It doesnt' have advanced features of mailman or ecartis.

**Comment by icy** [comment]
We will use lists provided by http://www.freelists.org
