### ISSUE TITLE
Clean hotkey + provide good hotkey support for uim-vi

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#22]
I've pushed a new patch for `uim-vi` at https://github.com/TheSLinux/buildsystem/tree/uim-vi/uim-vi

Please compile and install this package on your computer, and configure it in the best way that you want to use `uim`.

All user's configuration is stored in `~/.uim.d/`, so you need to remove/backup your old configuration before starting brand new configuration for `uim-vi`. After that you use the problem `uim-pref-gtk`  to configure `uim`.

Topics that you need to concern
- Hotkey for input method switching
- Hotkey for input method toggle (on/off)
- List of default input methods
- Remove all unneccessary hotkeys

When you're done, please attacch the configuration files `~/.uim.d/` to the list. It's optinal that you can create a patch.

**Comment by icy** [comment]
Huy đề nghị một số phím tắt cho tốt nhé. Mình sẽ ít thay đổi các phím tắt này.

Hiện anh đang dùng
- **Control Alt Blackslash**: để chuyển giữa các kiểu gõ (nhưng không bao gồm gõ Direct)
- **Super Escape**: để bật / tắt các bộ gõ (global setting)

**Comment by NgoHuy** [comment]
Hiện tại em đang dùng:
- On/off: _Control_space
- Chuyển bô gõ: Alt+n

Các phím tắt khác hầu như không quan trọng nên giữ nguyên hoặc xoá sạch.

**Comment by icy** [comment]
Bỏ **^Space** vì nó thường được dùng cho **autocompletion**. Em có thể
làm điều tra nho nhỏ với các bạn khác xem.

## 

I am ... 5 dog years old.

**Comment by icy** [comment]
Bộ phím tắt không cần chọn theo thói theo của em, mà chọn
- sao cho có thể dùng lâu dài, tới năm 2023 nếu có thể :)
- không đụng với bộ phím tắt của e17 (trong e17 sẽ có rất nhiều tổ hợp sẽ xây dựng lại)

**Comment by NgoHuy** [comment]
đã nhận.

**Comment by icy** [comment]
Huy em thử dùng `profile` này xem https://github.com/TheSLinux-forks/126-uim-vi . Có gì gửi feedback để anh hoàn thiện.

**Comment by NgoHuy** [comment]
Dạ đầu tiên em gặp phải là phím super em không rõ là phím gì, có lẽ là phím windows nhưng vẫn không bật tắt bộ gõ được, các phím còn lại đều không mấy khó khăn để quen và nhớ.

**Comment by icy** [comment]
Để a viết cái hướng dẫn tiếng Việt. Trong `126-uim-vi`  a đã ghi rõ cách làm. Khi bật lên thì mặc định sẽ không có bộ gõ tiếng Việt, em dùng `^ Alt \` để chuyển qua bộ gõ e cần. Khi bộ gõ đã bật thì sẽ có trạng thái của nó là `on` hay `off`, khi đó mới dùng `Super Escape` để chuyển. Hoặc có thể tạm thời chuyển về kiểu `direct` bằng phím `^ Alt Space`.

**Comment by icy** [comment]
Anh đã `push` gói riêng tên là `126-uim-vi` trong hệ thống `buildsystem`, sau khi cài vào thì các profile mặc định sẽ có trong `/usr/share/theslinux/126/uim.d/` . Hiện vẫn chưa có cách nào dùng `profile` này hiệu quả :D

**Comment by NgoHuy** [comment]
ah, cái path thì có trong file `uim/uim-custom.c` có đoạn mã sau:

```
# edit lại bài dán đoạn mã nguồn vô đây nhé Huy. Bờm quá :D 
```

**Comment by icy** [comment]
Gợi ý hay, nhưng tạm thời dùng cách khác không phải "xử" đẹp như vậy đâu =))

## 

I am ... 5 dog years old.

**Comment by NgoHuy** [comment]
ah, cũng có biến môi trường `LIBUIM_SCM_FILES` hiện em chưa rõ nó dùng như thế nào :D

**Comment by icy** [comment]
Ghi chú lại sau tìm em, làm cái khác đi :D

**Comment by icy** [comment]
Huy xem trong http://theslinux.org/doc/uim-vi/126-uim-vi/

**Comment by icy** [comment]
Tạm ổn. Đóng lại :)
