### ISSUE TITLE
g1 to be moved to gs

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#23]
Because github doesn't support `issue moving` (between projects) we need common name/project for all generations. So we need to move this project `g1` to `gs` (here `s` means there would be many generations). We will use `Milestone` in Github to specify generation then.

This is only a notification. When you're ready please let me know I will move the project.

Some old links (for example, links from the project `Bogo` would be broken). We also need to create a new project `g1` with some simple guidline.

**Comment by NgoHuy** [comment]
Okay. I'm ready
