### ISSUE TITLE
Export, backup and mirror all issues on Github

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#24]
- Find a way to export issues from github, to
- Backup them
- Push them to any mirror on the internet (nabble ?)

**Comment by icy** [comment]
Question: is there any way to add an external email to follow the discussion on Github?

**Comment by icy** [comment]
Xem thêm
- https://github.com/afresh1/rt-ticket-import-export
- https://npmjs.org/package/github-issues-export

**Comment by xluffy** [comment]
Backup ra dạng gì vậy anh, có nhất thiết là phải đọc lại không?

Cái này thì sao anh: https://api.github.com/repos/TheSLinux/gs/issues

**Comment by icy** [comment]
Em xem thử các `tool` mà a chỉ ra ở trên nó hỗ trợ thế nào. Nói chung là ra dạng gì cũng được, miễn là có thể `parse` lại sau này (ví dụ, ra dạng `HTML` thì mình có thể dùng `Nokogiri`, bla bla).

Một lưu ý nhỏ, là do các thông tin trên ticket có thể điều chỉnh lại được, nên có thể phải chạy đều đặn thường xuyên để xuất ra.

Cái `api` ở trên thì hay thật, nhưng chưa rõ `spec` của nó thế nào, có xuất ra tất cả các `ticket` hay không? (Về định dạng thì đó là `json` có thể dùng rất tốt cho các `tool` sau này.)

**Comment by icy** [comment]
- Isssues: https://api.github.com/repos/rails/rails/issue
- Comments: https://api.github.com/repos/TheSLinux/gs/issues/24/comments

**Comment by icy** [comment]
API usage policy http://developer.github.com/v3/#rate-limiting

**Comment by icy** [comment]
assign luffy => icy

**Comment by icy** [comment]
Sử dụng hệ thống mail để sao  lưu các thông tư kể từ ngày hôm nay.
TODO: Liên hệ github để lấy mxbox cũ, hoặc chuyển tin từ email cũ sang.

**Comment by icy** [comment]
Đóng chủ đề này lại thôi :)

**Comment by icy** [comment]
https://gist.github.com/unbracketed/3380407
