### ISSUE TITLE
telex/uim: không gõ được từ English 

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#26]
Huy kiểm tra lại giúp anh xem. Khôn gõ được từ đó :)

Ngoài ra cách phản ứng của w cũng khá lạ. Ví dụ khi gõ các từ **walker**, **w**, **woh** và **tow**

**Comment by icy** [comment]
Trong các bộ gõ khác anh nhớ khi dùng phím nào đó thì sẽ tạm thời chấp nhận từ . Không rõ tính năng này trong `uim` là gì

**Comment by NgoHuy** [comment]
anh phải bỏ check cái annotation dict server đi sẽ ổn

**Comment by icy** [comment]
On Sat, 13 Apr 2013 19:40:55 -0700
Ngô Huy notifications@github.com wrote:

> anh phải bỏ check cái annotation dict server đi sẽ ổn

Anh không xài nó mà. Bộ em không bị sao hả !?

Gõ E.n.g.l.i.s.h (Kiểu xtelex) sẽ bị , chỉ còn `ish` thôi hehe

**Comment by icy** [comment]
Xác nhận là anh vẫn bị với `UIM/xtelex` nhé, bất kể cài đặt của Annotation thế nào.

**Comment by NgoHuy** [comment]
xác nhận là em cũng bị với nhiều từ vơi xtelex.

**Comment by icy** [comment]
Cái này chắc để từ từ tìm hiểu xem, vì anh chỉ chuyển 1-1 từ bảng của `scim` qua. Tạm thời cứ dùng và đánh giá nó xem nhé. Nếu cần mình có thể chỉnh lại trong bản gốc thôi.

**Comment by icy** [comment]
Lưu ý là khi dùng `xtelex` thì gõ dấu thường là cuối từ. Đây là bộ tự điển riêng nên cũng có nhiều điểu không thống nhất, cần cải tiến nhiều.

**Comment by NgoHuy** [comment]
có vẻ lỗi này cần remove các phím commit trong phần `global keybinding 1` để trống thì ổn. Em đang gõ xtelex và thấy ổn anh ah.
Vài chỗ là cần để dấu ngay sau nguyên âm thay vì tự do cần định nghĩa lại các từ không anh ?

**Comment by icy** [comment]
Định nghĩa lại cũng dễ thôi nếu e thấy cần thiết và có ích. Đổi gì thì làm từ bản gốc 

https://github.com/icy/myquartz-scim2uim/blob/master/src/Telex.txt.in

(anh không rõ bản này còn dùng trong Scim được không nhưng cách đổi bảng này thì rất đơn giản, sau đó dùng kịch bản anh viết để đổi qua bảng của `UIM`.)

**Comment by icy** [comment]
Có thể đã tìm ra nguyên nhân và sẽ khắc phục sớm.

**Comment by icy** [comment]
Ví dụ, với bản điều chỉnh đã có thể gõ được từ Apache (ache, acht, ..) nhưng trong bản cũ không thể gõ được các từ này.

**Comment by icy** [comment]
Anh đã fix được lỗi :D kết quả rất khả quan, bây giờ có thể gõ các từ English, Apache, ... bình thường. Em coi trong kịch bản `/bin/find_missing.rb`.

Kết quả để trên repo chính https://raw.github.com/TheSLinux-forks/myquartz-scim2uim . Để sử dụng cần
- Lấy gói `uim-vi` mới nhất
- Xóa đi các tập tin `Telex.txt.in`, `VNI.txt.in` và `scim2uim.rb` do `makepkg` tải về từ lần đóng gói trước đây.

(Đây là cách quy tắc chung sau này sẽ không nhắc lại nữa.)

Cũng có thể tạo trực tiếp các tập tin `xtelex.scm` và `xvni.scm` nhờ kịch bản `scim2uim.rb` rồi chép các tập tin mới sinh ra vào `/usr/share/scim/x{telex,vni}.scm`. 

*\* TODO **
- Phần còn lại là chỉnh các lỗi của bảng `vni`. Hiện giờ không thể gõ ví dụ `7071` . 
- Thêm các định nghĩa cho bảng `telex`

**Comment by icy** [comment]
Các thử nghiệm trực tiếp: Walker, wow, tow, how, english, ache, apache, memory, markdown

**Comment by icy** [comment]
Vài hướng dẫn cho Hacker https://github.com/TheSLinux-forks/myquartz-scim2uim/blob/master/src/README.md

**Comment by icy** [comment]
Gõ **Muốn** phải bỏ dấu sau. Kiểu này chưa thống nhất vì nhiều từ bỏ dấu sau và trước đều được. Ví dụ **Trước** có thể gõ cả dấu sau hoặc trước.

**Comment by icy** [comment]
Lỗi với chữ **Muốn** đã khắc phục trong https://github.com/TheSLinux-forks/myquartz-scim2uim/commit/137419ca841c2c1fe1b88cab2cc8135525741e22

**Comment by icy** [comment]
Gõ **software** hơi khó, sẽ ra **softưare** vì sử dụng định nghĩa cho **wa**. Đây là cách gõ nhanh, nhưng việc sử dụng **w => ư** là điều nên tránh vì sẽ làm việc gõ nhiều từ tiếng Anh khó khăn hơn.

**Comment by icy** [comment]
Đã gõ nhanh được **software** nhờ bỏ đi định nghĩa gõ tắt **wa**. Xem trong https://github.com/TheSLinux-forks/myquartz-scim2uim/commit/5fc168b910b2e5eceede7276a4612d6f9904e8e9

**Comment by NgoHuy** [comment]
Em đã lọc và bỏ hết từ có w thành ư. Hiện tại, cần lọc lại những từ không có hoặc không bao giờ đúng như Uốc =>> chữ Uốc viết hoa chữ U đứng riêng không có nghĩa hay Ãch,... ưỡp. Đồng thời em cũng bỏ inputpad trong toolbar của uim.

**Comment by icy** [comment]
Nhớ pull về chỉnh rồi tạo pull request nhé . A mới push thêm nhiều đó.

**Comment by icy** [comment]
Không gõ từ **groups** tiếng Anh được. Gõ sẽ ra **groúps**. Cách khắc phục: Thêm định nghĩa **upss => ups**. Huy xem và chỉnh nhé

**Comment by NgoHuy** [comment]
em chỉnh là oups -> oups như thế gõ sẽ không bị nhập 2 lần chữ s mà tiện gõ luôn .

**Comment by icy** [comment]
cái này không liên qua tới _o_, nên chỉ cần chỉnh cho **úps** thôi (nếu không sẽ không gõ được tên công ty **UPS**). Theo cách bỏ dấu ở sau (mình sẽ gần như hỗ trợ cả hai kiểu bỏ dấu phải không !?),  thì **ups** sẽ thành **úp** nên không hiểu cái Huy nói là gì !?

**Comment by NgoHuy** [comment]
Em đã hiểu :+1:

**Comment by icy** [comment]
Không gõ được **u a a j t**, nhưng gõ được **u a a t j**. Dạng bỏ dấu phía trước có thể có bằng cách thêm ánh xạ **uaaj => uậ** .

**Comment by icy** [comment]
Gõ từ **u y e n** không được.

**Comment by icy** [comment]
Huy đang làm trên mấy cái này không có `fix` được cái nào chưa?

**Comment by NgoHuy** [comment]
Hiện tại, em đang làm thì thấy rằng cách gõ nhiều người khác nhau, bỏ dấu sau trước, cách fix thì chỉ có thể định nghĩa lại từ đó hoặc sửa cách gõ, em đang làm là sửa cách gõ, bỏ dấu sau nguyên âm là phỏ biến nhất trong bảng định nghĩa của Telex.

Hiện em fix được những từ đó bằng cách định nghĩa lại file Telex.in. Tuy nhiên những chữ như *uân, *uôt hay *uật thì việc bỏ dấu trước phụ âm  như n hay t cuối thì đều bị lỗi.
Hướng khắc phục tạm thời định nghĩa : 
- uaajn -> uận
- chữ uyen do không được định nghĩa (chỉ có uyên nên phạm luật) định nghĩa lại uyen -> uyen. Các trường họwp này đều là do định nghĩ có dấu chứ không có định nghĩa cho không dấu (thật ra uyen không đứng 1 mình và cũng không có nghĩa )

**Comment by icy** [comment]
A đã `fix` cho tất cả các chữ cuối (ups, uyen, luật) trong bản mới nhất . Em có thể tham khảo cách làm. Và kể cả tập tin `Makefile` a mới tạo ra trong đó.

https://github.com/TheSLinux-forks/myquartz-scim2uim/commit/1350951bc0c9c0e2c6ec647e0542a447b054ef60

Do bản gốc chỉ định nghĩa kiểu gõ sau, nên để hỗ trợ cả kiểu gõ trước thì sẽ có xu hướng phình ngày càng to, có thể lên trên 50% bảng hiện tại.  Và nếu không làm cẩn thận, sẽ dẫn tới việc chấp nhận các từ sai, và sẽ giống hệt bản của `scim`.

Đây là vấn đề lâu dài nên Huy có thể làm từ từ. Hiện giờ bảng `vni` vẫn còn để ngỏ em có thể nhờ một bạn nào giúp.

Lưu ý là cách làm vẫn là `pull`, `push`, em fork kho trên về và tạo `pull request` cho từng feature e cần sửa để `merge` dễ hơn.

**Comment by icy** [comment]
làm thế nào để tránh tổ hợp này ta **âợ** :)

**Comment by icy** [comment]
Đã thu gọn bản `telex.txt.in` về còn khoảng 1000 dòng, fix vài lỗi và bỏ đi các tổ hợp vô nghĩa. Xem thêm trong bản `v1.0.0` https://github.com/TheSLinux-forks/myquartz-scim2uim/tree/v1.0.0 .

**Comment by icy** [comment]
Bảng Telex còn 929 định nghĩa. Bảng VNI cũng đã được tuốt lại .

**Comment by icy** [comment]
Các lỗi cơ bản đã fix, nhưng cần dùng và kiểm tra kỹ hơn kể cả hai bảng mã VNI và Telex. Đặc biệt là VNI hiện không có người kiểm tra.

Tạm đóng chủ đề này lại. Nếu có vấn đề mới vui lòng mở ticket mới. Cảm ơn.

**Comment by icy** [comment]
Tiếp: không gõ được `moosefs.org` một cách dễ dàng được :D  (bản 1.4.1 của `uim-vi-telex`)

**Comment by icy** [comment]
Từ này khó gõ là do định nghĩa `ooos` thành `oó` để gõ một số từ đặc biệt như `moóc-phin`, `quần soóc`, .... nhưng lại không đi kèm `cancel form` cho nó. :)

**Comment by icy** [comment]
Fix in https://github.com/TheSLinux-forks/myquartz-scim2uim/commit/3204bdb011d9bf77ba4dda53d4e9e79878bf4880
