### ISSUE TITLE
Git training

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#28]
Help developers to use Git effectively

**Comment by vothailam** [comment]
Chưa thấy có lịch cụ thể nhỉ?

**Comment by icy** [comment]
On Tue, 16 Apr 2013 21:38:38 -0700
vothailam notifications@github.com wrote:

> Chưa thấy có lịch cụ thể nhỉ?

Hi Lâm đang chuẩn bị tài liệu và có thể dời lại, mình sẽ thông báo sớm.
Do Huy đang bận thi nữa nên chưa vội :D 

## 

I am ... 5 dog years old.

**Comment by icy** [comment]
(Mình định tuần này mà quên mất tuần này với tuần sau đều trúng dịp lễ nên thôi :D)

**Comment by icy** [comment]
Lâm theo dõi trang này và trang Doodle http://theslinux.org/events/2013/05-git-training/ khi nào có ngày tháng thì Lâm sắp xếp giúp phòng ốc và thiết bị nhé (chỉ cần một máy chiếu để làm demo). Cảm ơn Lâm.

**Comment by icy** [comment]
(Trang Doodle có cho ở địa chỉ của Event ở trên)

**Comment by ghost** [comment]
+1 
Cái này rất cần thiết, trong khi dev ở VN chưa quen với git lắm :)

**Comment by icy** [comment]
Cảm ơn _rhacker_ :)

**Comment by icy** [comment]
Sẽ tiến hành vào 9h sáng ngày 5/5/2013

**Comment by ghost** [comment]
hình ảnh update về sự kiện sẽ được update ở đâu @icy

**Comment by icy** [comment]
Cảm ơn _rhacker_ đã quan tâm. Hiện giờ chưa có ảnh nào :D Sáng mai mình mang máy theo chụp, có gì sẽ update lên trang FB của dự án https://facebook.com/theslinux/

**Comment by ghost** [comment]
nice :) 
looking forward to it.

**Comment by icy** [comment]
Mình đã viết vài dòng trên SaigogLUG và ArchLinuxVn. Hình chỉ chụp hai cái cũng giống nhau nên úp lên một :P
https://www.facebook.com/photo.php?fbid=514602428587068

Buổi tập huấn này không tốt như mong đợi :) Nhiều bạn đăng ký mà không đi, đi trễ . Hy vọng lần sau sẽ khá hơn.

**Comment by ghost** [comment]
```
Yêu cầu: Biết gõ bàn phím
```

Love this :D

**Comment by icy** [comment]
haha, chủ yếu giới thiệu ý tưởng , cách làm việc thôi. Nhiều khi cứ cắm đầu làm không để ý tưởng thiết kế của `git` thế nào ấy mà. Nên yêu cầu vậy là hợp lý rồi :P
