### ISSUE TITLE
e18 pre-defined profile

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#29]
E17 has a great and complex set of settings. We need to define some common aspects of our GUI, that
- is stable and won't be changed in a near future
- good and flexible
- support 8 virtual desktop by defaults
- has no border for some common applications
- remember the virtual desktop for some common applications

The common applications are some sample roups
- browser
- instant messenger (pidgin, skype, bla bla)
- editor (abiword, openoffice,...)
- shell (this will start by default !?)
- email client,
- file manager
- ...

Every time user logs in to the system they should see the old settings!!!

**Comment by icy** [comment]
Mấy cái nào đánh dấu **_high** Huy coi làm trước nhé.

**Comment by NgoHuy** [comment]
Vấn đề lưu lại thuộc tính thì đã có phân vùng `Persistent` lưu lại khi tạo usb boot.

**Comment by icy** [comment]
Anh nhớ lâu rồi `e17` có một tiện ích để `dump` các cấu hình của nó ra dạng `text`. Không rõ là nó có thể làm ngược lại không. Em kiểm tra xem nhé. Nếu chỉ công bóo dạng `binary` như em làm ở nhánh `e17_config` thì a hơi ngại !!!

**Comment by NgoHuy** [comment]
:+1:
Em cũng đang tìm cách dump ra text thay vì binary, tạm thời em config theo README.md của e17_config :-)

**Comment by icy** [comment]
Dump ra rồi dịch ngược trở lại chắc là có cách e hỏi đội `e17` kỹ hơn về cách làm nhé.

**Comment by NgoHuy** [comment]
Hôm qua em lên #e hỏi thì có 2 lệnh đã dump và dịch ngược thành công là `eet`

`eet -d /path/to/*.cfg config > out_file` (dump file)
`eet -e out_file.cfg config out_file 1` (biên dịch ngược lại, 1 để chỉ nén file hoặc 0 là bỏ qua nén)

Tuy nhiên một số dile bị lỗi `ERR<889>:eet_main bin/eet/eet_main.c:233 do_eet_decode() cannot write to standard output` do kích thước file quá nhỏ hoặc file rỗng. Chỉ có 1 từ khóa là config để dump và biên dịch ngược vào.

**Comment by icy** [comment]
Ok có tiến bộ rồi, cố gắng lên nhé :) Chắc chắc phải có cách, thậm chí có thể phải viết chương trình `C` nữa :D Nhưng như thế sẽ tiện cho việc bảo trì hơn nhiều.

**Comment by icy** [comment]
Huy phải khẳng định hay phủ định là có thể dùng công cụ `dump` để quản lý cấu hình của `e17` ở dạng `plain text` không. Tạm thời không chấp nhận phân phối cấu hình `e17` ở dạng `binary` nên cần tìm cách giải quyết triệt để vấn đề này.

**Comment by NgoHuy** [comment]
Em khẳng định `dump` có thể dùng để quản lý cấu hình của `e17`. Tạm thời không có `công cụ` nào làm được việc `dump` `binary` của `e17` ra `plain text` cả.

**Comment by icy** [comment]
1. Khi có tập tin cấu hình, làm thế nào để chuyển thành dạng nhị phân cho `e17`?
2. Các tập tin nhị phân cuối cùng có phụ thuộc vào kiến trúc máy tính hay không?
3. E để tạm các tập tin cấu hình trên `repo` nào đó a sẽ chuyển vào kho `Theslinux-folks` sau.

**Comment by NgoHuy** [comment]
```
eet -d /path/to/*.cfg config > out_file (dump file)
eet -e out_file.cfg config out_file 1 
# (biên dịch ngược lại, 1 để chỉ nén file hoặc 0 là bỏ qua nén)
```

Các tập tin không phụ thuộc vào kiến trúc máy tính.

**Comment by icy** [comment]
Các việc cần làm
1. Tạo một `repo` riêng, có tên `126-e17`, trong đó có lưu các cấu hình của `e17` dạng mẫu, ở dạng `text`
2. Đặt `repo` ở trang `github` của riêng @NgoHuy 
3. Đặt ra các phím tắt . Không nhớ là @NgoHuy  đã nói ở đâu về một số phím tắt, hãy liệt kê ra lại nhé. Trao đổi ở đây hoặc trên nhóm thư đều tốt.

**Comment by NgoHuy** [comment]
Done !
https://github.com/NgoHuy/buildsystem/commit/11b9a6dead16a82e759f824b3b794d329035f1c0

**Comment by icy** [comment]
A coi mãi không hiểu vì sao @NgoHuy  để số `127`, giờ mới phát hiện ra a ghi nhầm ngay từ ban đầu. A sẽ tự chỉnh lại hihi . Thanks @NgoHuy

**Comment by icy** [comment]
Đổi chủ đề e17 => e18
