### ISSUE TITLE
Thiết kế logo

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#3]
Tạo một logo đơn giản cho dòng G1

**Comment by icy** [comment]
M ơi e coi giúp anh được không :) Hoặc giới thiệu cho anh cách!

**Comment by mitsukiAR** [comment]
là sao ạ? em ko hiểu gì hết anh ơi @___@!!!

2013/3/4 icy notifications@github.com

**Comment by icy** [comment]
Ah a nhờ em làm cái logo cho Slinux đó mà :) Để khi gặp em trên kênh
irc a sẽ nói rõ hơn

On Sun, 03 Mar 2013 12:34:36 -0800
Mitsuki Rainde notifications@github.com wrote:

> là sao ạ? em ko hiểu gì hết anh ơi @___@!!!
> 
> 2013/3/4 icy notifications@github.com
> 
> > M ơi e coi giúp anh được không :) Hoặc giới thiệu cho anh cách!

## 

I am ... 5 dog years old.

**Comment by icy** [comment]
Phông đề nghị http://www.1001fonts.com/blackchancery-font.html#styles

**Comment by icy** [comment]
Anh làm thử ở đây rồi @mitsukiAR  xem thử nhé https://github.com/theslinux/media

**Comment by icy** [comment]
Tạm thời chọn logo và màu như trong kho `media` đã chỉ ra. Sau này sẽ điều chỉnh lại cho đẹp hơn.

**Comment by thuandt** [comment]
:+1: 
Logo đẹp rồi

**Comment by icy** [comment]
Thanks @mrtuxhdb :)

Ý @mrtuxhdb nói cái này phải không https://www.facebook.com/photo.php?fbid=515067735207204&set=a.511112808936030.1073741825.488531607860817&type=1&theater ?

Hiện có hai bản, một bản ngắn chỉ gồm hai chữ `T` và `S` ghép lại. Bản dài có nguyên dòng chữ `TheSLinux`. Hai bản này đều chỉ dùng một màu `primary` trong bảng màu `scheme0` (mình có chỉ ra trong repo `media`), mà không dùng thêm màu `secondary`. Tuần tới mình sẽ có cơ hội gặp một họa sĩ, có thể được góp ý thêm về bố cục và màu sắc.

**Comment by icy** [comment]
Xong phần logo . Trên kho `media` vừa có cả kịch bản để tạo ra `favicon.ico` dùng cho các trình duyệt. File sinh ra đã được thêm vào trong khoa `home` để thể hiện trên trang chủ.
