### ISSUE TITLE
Firefox profiles

### ISSUE THREAD

**Issue by NgoHuy** [TheSLinux/gs#31]
Em đề xuất 5 addon sau cho profile của Firefox:
- Noscripts ( https://addons.mozilla.org/en-US/firefox/addon/noscript/ )
- Https-everywhere ( https://www.eff.org/https-everywhere )
- Flagfox ( https://addons.mozilla.org/en-US/firefox/addon/flagfox/ )
- Adblock plus ( https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/ )
- Flashgot ( https://addons.mozilla.org/en-US/firefox/addon/flashgot/ )

**Comment by icy** [comment]
Em coi xem có cơ chế gì quản lý các `add-ons` của Firefox thông qua dòng lệnh hay các file cấu hình không. Hoặc chỉ cần `trigger` để `firefox` cài các `add-ons` trên là được. Việc dùng các `add-ons` gì thì cũng cần có lý do và cũng không cần chọn nhiều quá. Cái này sẽ trao đổi sau.

**Comment by NgoHuy** [comment]
Em đã xem qua cách dùng dòng lệnh tuy nhiên không có cách nào cài cài qua dòng lệnh mà không dùng GUI cả, cách cấu hình là nó để tất cả các config addon trong thư mục .mozilla/firefox/<tên profile.defalt>
Em đề xuất 5 addons trên trên để gia tăng bảo mật cho firefox khi lướt web, trừ flashgot để tải tập tin thì còn lại cho mục đích đó.

**Comment by icy** [comment]
Huy biết cơ chế xác thực các **add-ons** của Firefox không? Làm thế nào để đảm bảo rằng **add-ons** nào đó đã được xác thực / kiểm tra / đáng tin ?

**Comment by NgoHuy** [comment]
Mọi addons có trong bộ sưu tập addons của mozilla ( https://addons.mozilla.org/en-US/firefox/) đều được nhóm Mozilla addons kiểm duyệt trước khi được chấp nhận ( https://addons.mozilla.org/en-US/developers/docs/policies/reviews )
Các addon không có trong bộ sưu tập cần xem xét trước khi cài đặt. Ở trên, chí có https-everywhere là ngoài bộ sưu tập nhưng có review khá cao từ người dùng (https://www.eff.org/https-everywhere)

**Comment by icy** [comment]
Nằm ngoài thì chịu em ơi.

**Comment by NgoHuy** [comment]
Dự án Tor cũng dùng https-everywhere nên em cho rằng đây cũng là một chứng minh rằng https-everywhere an toàn để cài đặt anh ah :-)

**Comment by icy** [comment]
Em chứng minh kiểu này thì làm một chặp trái đất sẽ có hình vuông đó em.

**Comment by NgoHuy** [comment]
Vậy tạm thời không lấy addons từ bên thứ 3, nằm ngoài bộ sưu tập của Mozilla cho chắc chắn :-)

**Comment by NgoHuy** [comment]
một số lý do không đưa vào bộ sưu tập của Mozilla:

>  Why isn't HTTPS Everywhere available for download from addons.mozilla.org like most other Firefox add-ons? 
> 
> A. We felt that the Mozilla privacy policy that applies to downloads from addons.mozilla.org is somewhat less protective than the privacy policies of the organizations that develop HTTPS Everywhere, and we prefer for HTTPS Everywhere users to be protected by our privacy policy. This decision could change in the future as Mozilla's privacy practices evolve or as we re-examine the details of the current Mozilla policy. `

**Comment by icy** [comment]
Chỉ là một "feeling" mà . Nhưng đó là quyết định của họ, không phải của Mozilla.

**Comment by NgoHuy** [comment]
tạm thời bỏ qua hết các addons không nằm trong bộ sưu tập của Mozilla tập trung vào các issue đựơc đánh dấu high nhé anh :-)

**Comment by icy** [comment]
Em nói gì a không hiểu.

**Comment by xluffy** [comment]
Mấy cái này nghĩ là FF sẽ mặc định (ở phiên bản nào đó) với các add-on này sau khi cài TheSLinux xong phải không. Có Flashgot mà không có DTA thì kì quá. Còn cái Flagfox mình thấy chả cần thiết.

**Comment by icy** [comment]
Vẫn chưa kết thúc danh sách cuối Quang ơi. Về cái profile này a đã tính tới nhưng chưa ra tới "mã" triển khai thôi. Danh sách ở trên chỉ là đề nghị, tạm gọi là "mặc định". Nhưng a cũng không chắc là sẽ có ngay trong dòng g1 hay không vì còn nhiều vấn đề lắm.

## 

I am ... 5 dog years old.

**Comment by icy** [comment]
Một bài rất hay http://askubuntu.com/questions/73474/how-to-install-firefox-addon-from-command-line-in-scripts

**Comment by thuandt** [comment]
Đống addons của Firefox cũng chỉ là file zip được sign thôi mà, một số cái khi cài nó extract ra để chạy một số không (với các phiên bản hiện tại).

Có thể đóng gói các addons này lại để người dùng có thể lựa chọn sẽ dùng addons nào.

**Comment by NgoHuy** [comment]
Vì TheSlinux là phiên bản pre-define, nên em tạm thời thêm một số addons vào, nếu không thích người dùng có thể gỡ ra, Những addons trên em đang dùng, vấn đề addons tạm gác lại sau những vấn đề được đánh dấu high.

**Comment by icy** [comment]
Có hai vấn đề khác nhau, do Huy mở chủ đề này chưa rõ ràng. Nhưng tạm thời chủ đề này bàn về danh sách các `add-ons` chọn ra làm mặc định, trong một `profile` mẫu mà người dùng có thể bỏ qua sau này. Về cơ chế chuyển thì xem ở #38. 

@NgoHuy Do các bạn khác đã bắt đầu `join` vào nên vấn đề gì đang làm hoặc trễ lại thì e chịu khó update status để mọi người theo dõi cho tiện. Vấn đề nào khá nhằn hoặc cần suy nghĩ thêm thì có thể `nhả ra` để trao đổi thêm.

**Comment by icy** [comment]
Liên quan tới các `add-ons` được chọn, @NgoHuy có thể kết lại vài tiêu chí cơ bản, ví dụ
- `add-ons` được chứng thực thế nào
- làm thế nào để `add-ons` được đánh dấu là đáng tin (và đáng tin tới mức nào, tức là có cơ chế nào phá vỡ niềm tin đó không?)
- v.v...

Các vấn đề này sẽ được cụ thể hóa thành tài liệu chính thức, ở dạng tiếng Việt để theo dõi cho tiện.
