### ISSUE TITLE
Bảng candidate trong uim

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#32]
Dùng các tùy chọn để tắt bảng `candidate` đi, thì bảng này chỉ thật sự tắt khi dùng `uim/xtelex`, còn `uim/scim-telex` vẫn còn hiện ra.

Huy kiểm tra xem tại sao và có thể thêm tùy chọn để tắt bảng đó đi nhé.

**Comment by icy** [comment]
Mình đã có tùy chọn tắt bảng `candidate` rồi mà nó vẫn hiện ra. Em xem thử cách mà `scim-telex` sinh ra bản popup đó và tắt đi. Có thể `scim-*.scm` ghi đè cấu hình nào đó.

**Comment by NgoHuy** [comment]
Không anh, em vừa hack code thì thấy nó dính liền với gtk và qt luôn ,e đang patch thử. Cái này bị ở chỗ là xtelex hay xvni đều không có cấu hình trên uim chuẩn (generic nên chịu kiểm sóat của (other input method) còn lại bị dính với uim source nên chịu kiểm sóat của lib-uim.so (dính vào gtk và qt)

**Comment by icy** [comment]
Có tùy chọn để tắt bảng `candidate` đi, em coi tùy chọn đó được dùng thế nào , chắc là không phức tạp lắm đâu.

**Comment by icy** [comment]
Anh đang coi cái này Huy có thể tập trung vào các vấn đề khác.

**Comment by icy** [comment]
Đã fix (xem nhánh **p_uim-vi@fix-candidate-option**), xem trong https://github.com/TheSLinux/buildsystem/commit/9f4b8c3c07b4c6a24f93ea51a57a2c227e6dd699

**Comment by NgoHuy** [comment]
wao, good job :+1:
