### ISSUE TITLE
Chế độ mặc định cho uim/xtelex

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#33]
Khi chuyển qua bộ gõ **uim/xtelex** cần bật bộ gõ này mặc định (hiện giờ khi chuyển qua bộ gõ này thì nó sẽ tự động tắt, phải mất công bật lên lại).

**Comment by icy** [comment]
Đã chỉnh trong miếng vá mới nhất https://github.com/TheSLinux/buildsystem/commit/6317b4b2cbbd4f9b8e503d5659ac309494919849

**Comment by icy** [comment]
Hiệu ứng phụ: Khi cho phép kiểu gõ thay đổi theo từng khu vực gõ (`text-area`) thì sẽ rất phiền toái, vì các kiểu gõ mặc định sẽ được kích hoạt. Khi đặc chế độ mặc định ON cho các kiểu gõ Generic, thì cách tốt nhất là cho phép kiểu gõ thay đổi ở mức ứng dụng .

Có một điều hơi "lạ" khác: Nếu tắt kiểu gõ cho một ứng dụng, thì khi `focus` không nằm trong khu vực gõ chữ nào thì biểu tượng sẽ vấn hiện kiểu gõ là ON :)

**Comment by icy** [comment]
@Huy kiểm tra xem miếng vá mới có tốt như mong đợi không nhé. Nếu không sẽ dùng phương án khác, đó là thêm một tuỳ chọn cho phép người dùng chọn chế độ mặc định cho các kiểu gõ Generic.

**Comment by NgoHuy** [comment]
Em dùng và thấy tốt, như mong đợi.

**Comment by icy** [comment]
Đang thêm miếng vá khác ngon hơn. Việc đặt cứng thiết lập mặc định là không nên.

**Comment by icy** [comment]
Xem trong https://github.com/TheSLinux/buildsystem/commit/151d404b9cfe780c16dd7ade0d015a8c9864e1a0
