### ISSUE TITLE
Báo lỗi cú pháp khi sử dụng bộ gõ uim

### ISSUE THREAD

**Issue by xluffy** [TheSLinux/gs#34]
Hiện tại mình bị với các từ này:

sứong -> suowngs
voíw  -> voisw
suớwng -> suowwngs 

-> thường thì những từ có vần ư và vần ơ đi liền nhau trong các bộ gõ trước đây mình sử dụng thường sẽ gõ như sau:
- Gõ chứ "u" tiếp đến là chữ "o" rồi mới gõ chứ "w" thì tự động nó sẽ thành "ươ" nhưng với uim nó sẽ ra "uơ" 
- hoặc nếu gõ chữ "u", "o" rồi gõ 2 lần chữ ww thì sẽ ra được chữ "ươ" nhưng với uim nó sẽ ra "uơw"

Kiểu gõ là m17n-vi-telex.

**Comment by icy** [comment]
Cảm ơn Quang. Những cái Quang báo có thể gọi là `bug`, có thể gọi là `feature`. Cũng như nhiều kiểu gõ khác, `m17n-db-telex` đặt ra các quy tắc gõ ở dạng **lập trình được**, sau đó thêm vào các ngoại lệ. Mình sẽ xem qua và sẽ trả lời liệu sẽ thêm các tính năng đó như thế nào.

Điều lưu ý là các hỗ trợ của `m17n-db-telex` gần với bảng chính thống https://vi.wikipedia.org/wiki/VNI  trong đó đặt ra các quy tắt về dấu. Việc thêm các tổ hợp mới vào là một cách tiện lợi, nhưng như a trao đổi với Huy và các bạn bên dự án bogo, các quy tắc thêm vào nên để ra ngoài ở dạng tùy chọn, người dùng có thể chỉnh được dễ dàng. Lý do cho việc này là việc thêm vào nhiều quy tắc thì sẽ gây cản trở trong một số tổ hợp tiếng Anh (ví dụ với kiểu gõ `m17n-vi-telex` thì gõ `world` hơi chậm, `xtelex` gõ `world` nhanh hơn)

Ngay cả với `xtelex` thì việc thêm vào không dễ, nhưng cách thêm vào rất trực quan, e có thể xem ở đây https://github.com/TheSLinux-forks/myquartz-scim2uim/blob/master/src/Telex.txt.in . 

Tạm thời anh để `ticket` này ở mức thấp (`_low`) a sẽ coi lại cách điều chỉnh trong bảng `m17n` và gửi phản hồi sau nhé.

**Comment by icy** [comment]
Ghi chú thêm: sẽ dùng `xtelex` và `xvni` mặc định. Anh sẽ thêm vào định nghĩa `uoww` để tránh tường hợp gõ nhầm như trao đổi trên kênh `irc`. Cảm ơn Quang nhiều.

**Comment by icy** [comment]
Anh đã thêm vào dạng `chỉnh lỗi` https://github.com/TheSLinux-forks/myquartz-scim2uim/commit/60613918364f83368e1de1db4d827e3b4ca763f6

Chưa có trong gói mới, nhưng em có thể lấy mã nguồn về và `make install` thôi

```
git clone git://github.com/TheSLinux-forks/myquartz-scim2uim.git
cd myquartz-scim2uim/src/
sudo make clean build install
```

Em cần có `ruby` trên hệ thống, với `locale` đặt đúng (`en_US.utf-8`).

**Comment by xluffy** [comment]
Okie, em sẽ thử.

Vào 07:47 Ngày 14 tháng 5 năm 2013, Ky-Anh Huynh
notifications@github.comđã viết:

> Anh đã thêm vào dạng chỉnh lỗi TheSLinux-forks/myquartz-scim2uim@6061391https://github.com/TheSLinux-forks/myquartz-scim2uim/commit/60613918364f83368e1de1db4d827e3b4ca763f6
> 
> Chưa có trong gói mới, nhưng em có thể lấy mã nguồn về và make installthôi
> 
> git clone git://github.com/TheSLinux-forks/myquartz-scim2uim.git
> cd myquartz-scim2uim/src/
> sudo make clean build install
> 
> Em cần có ruby trên hệ thống, với locale đặt đúng (en_US.utf-8).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TheSLinux/gs/issues/34#issuecomment-17861464
> .

## 

_Quang Nguyễn_

**Comment by icy** [comment]
Các vấn đề mà Q. báo đã điều chỉnh trong mã nguồn và giải thích trên kên #irc. Tạm thời đóng chủ đề này lại khi nào có vấn đề hãy mở lại.
