### ISSUE TITLE
Bộ kiểm tra chính tả cho các phần mềm tiếng Việt

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#36]
Huy xem có thể dùng bộ kiểm tra chính tả nào không?

**Comment by NgoHuy** [comment]
Em so sánh hai  bản 
- aspell ( http://aspell.net/ )
- hunspell-vietnamese (https://code.google.com/p/hunspell-spellcheck-vi/)

thì hunspell tốt hơn, có kiểm tra kiểu bỏ dấu cũ và bỏ dấu mới, trong khi aspell thì không.

**Comment by thuandt** [comment]
+1 hunspell

Có cần kiểm tra kiểu Anh-Việt lẫn lộn hem nhỉ? (với những người như em chẳng hạn thì việc viết lẫn lộn Anh-Việt là rất thường xuyên).

Nếu đã mặc định có bộ kiểm tra chính tả thì những trình khác như Firefox, Chrome có cần tùy chỉnh gì thêm không?

**Comment by NgoHuy** [comment]
Nếu bật hunspell thì chỉ cần bật kiểm tra chính tả ở ứng dụng, nó sẽ tự kiểm tra nếu không phải tiếng Việt thì sẽ báo.  Ngoại lệ Firefox phải thêm từ điển tiếng Việt (https://addons.mozilla.org/en-US/firefox/language-tools/)

**Comment by thuandt** [comment]
Vậy thì nếu có hunspell thì nên đi kèm cả từ điển chính tả cho Firefox nữa.
LibreOffice thì sao?

**Comment by NgoHuy** [comment]
LibreOffice chỉ cần bật check my spell lên ( hunspell là engine cần có từ điển đi kèm nên cần cài hunspell-vi như link ở trên )

**Comment by icy** [comment]
Trong `repo` của `Arch`, kể cả trong `AUR` chỉ thấy các hỗ trợ `hunspell` cho tiếng nước ngoài , không có tiếng Việt.

**Comment by NgoHuy** [comment]
Hiện tại, sau khi so sánh em đề xuất `aspell` với lý do sau
- `AUR` có `aspell` cho tiếng Việt [1], tuy nhiên bản `PKGBUILD` này lỗi, cần viết lại, em đã `build` thử và dùng tốt trên `gedit/abiword`. Bản `aspell` này cũng không kiểm tra bỏ dấu theo kiểu mới hay cũ.   
- Dùng gói `enchant` có trong `extra repo` để làm `generic spell checking` cho `aspell`
  [1] : https://aur.archlinux.org/packages/aspell-vi/

**Comment by icy** [comment]
A thấy không ổn lắm, lúc đầu em đề xuất cái khác, giờ lại cái khác, giờ biết tính sao đây? Nên đặt ra các tiêu chí tìm kiếm trước, ví dụ:
1. Có thể dùng tốt trong `abiword` và `libreoffice`  và có thể trong một số chương trình hay gặp khác
2. Được cập nhật hoặc có thể được cập nhật (bảo trì, bổ sung, phát triển) dễ dàng (hay ít ra là không khó khăn như những bộ kiểm tra chính tả khác.)
3. Không nhất thiết phải kiểm tra chính tả theo một kiểu bỏ dấu cụ thể, vì việc này về mặt kỹ thuật có thể giải quyết dễ dàng. Do cách xuất dấu truyền thống (hòa) được hỗ trợ mặc định, nên có thể ưu tiên cái này. Tuy nhiên, bộ quy tắc có thể dễ dàng nhân bản ra, ví dụ `foobar-vi` hay `foobar-vi-IPA`. **Do đó, việc bỏ dấu truyền thống hay theo IPA** không phải là một tiêu chí chọn lựa bộ kiểm tra chính tả.
4. Khả năng điều chỉnh dễ dàng từ phía người dùng. Ví dụ, giúp người dùng thêm vào các từ ghép có nghĩa, ví dụ `hoàng hôn` chứ không phải `hoàn hôn`, nhưng `hoàn trả` là một từ đúng. _(tuy nhiên, a không chắc có bộ kiểm tra chính tả nào hỗ trợ từ ghép :D)_.

**Comment by NgoHuy** [comment]
Ban đầu em đề xuất hunspell vì bản vi do người Việt Nam làm và có bổ sung kiểu bỏ dấu hiện đại. 

Tuy nhiên sau khi xem xét :
- Mỗi ứng dụng sẽ có một trình kiểm tra chính tả xác định mà nó hỗ trợ, vd: `abiword` hỗ trợ `aspell`, em dùng `hunspell` lại không được trong khi `LibreOffice` hỗ trợ `hunspell` 
- Các bản kiểm tra chính tả hiện tại đều không được cập nhật nữa,  mới nhất chỉ có hunspell-vi, còn lại đã rất lâu. Dễ và có thể cập nhật thì chỉ có từ điển của dự án hunspell-vi là có thể, nguyên mẫu của nó là `aspell dictonary` có thể dùng cho `aspell`
- Bản [1] có thể thay đổi theo ý người dùng với các tập tin hòan toàn là `plain text` :D 

[1] : https://hunspell-spellcheck-vi.googlecode.com/files/PackVietnamese.zip

**Comment by icy** [comment]
Kiểu bỏ dấu `IPA` không nên nói là kiểu "hiện đại" dễ gây nhầm lẫn. Hiện nay các báo chí đã quay trở lại cách gõ truyền thống.

Nếu chỉ có phương án duy nhất thì chắc phải hỗ trợ mỗi ứng dụng một bộ kiểm tra chính tả thôi. Khi nào đụng đến `libreoffice` sẽ tính sau. Câu hỏi là tại sao `hunspell` lại không dùng với `abiword`?

Việc bộ kiểm tra nào đó không cập nhật thì cần tìm hiểu lý do. Em tìm giúp a các email liên lạc a sẽ liên hệ với các developer nguyên thủy khi cần. (Khuyến cáo là e không tự viết các email liên hệ mất công a giải thích lại.) Ngoài ra xem tới khả năng điều chỉnh vào bảo trì nó như thế nào nữa. Ví dụ,  `unikey engine` rất tốt nhưng lâu ni chẳng có ai bảo trì, mà bạn nào mới xông vào thì chỉ có ngất ngây thôi, vì mã toàn `c/c++`.

**Comment by icy** [comment]
Huy nên làm cái bảng, mô tả chi tiết hơn, tổng kết lại giúp anh. Trình bày ở tài liệu `google doc` cho nó tiện cũng được. Thanks

**Comment by icy** [comment]
Anh mới coi qua, thấy `hunspell` hỗ trợ các từ ghép trong tự điển. Mặc dù `aspell` cũng có nhưng `hunspell` có vẻ tự nhiên hơn. Em kiểm tra lại. Ví dụ về từ ghép thì a đã đưa ở trên.

**Comment by NgoHuy** [comment]
Em mô tả như sau 
- Một chương trình muốn có `spell checking` cần hỗ trợ ở mức mã nguồn và xác định rõ chương trình [1], [2].
- `Hunspell` hỗ trợ thiết lập dưới dạng `plain text` tốt hơn `aspell` ( xem cụ thể file `.dic` và file `.aff` của `hunspell-language` )
- `aspell` đã không cập nhật từ năm 2004, còn `hunspell` do tác giả người Việt làm, dễ dàng liên hệ và viết `PKGBUILD`

Về mặt lợi thì rõ ràng `hunspell` nhiều hơn nhưng về mặt ứng dụng thì còn tùy ứng dụng. Do đó tạm thời giải pháp vẫn là nhiều chương trình hỗ trợ kiểm tra từ điển. 

[1] : http://aspell.net/0.50-doc/man-html/6_Writing.html
[2] : http://stackoverflow.com/questions/16430188/simple-c-console-app-using-hunspell

**Comment by icy** [comment]
Rốt cuộc là chọn cái gì là tốt nhất Huy?

**Comment by NgoHuy** [comment]
Em ghi rõ là nhiều ( ở đây là cả `aspell` và `hunspell` ).
Hiện giờ không có cái nào kiểm tra tòan bộ các ứng dụng.

**Comment by icy** [comment]
Vậy thử với `hunspell` trước xem :D

**Comment by NgoHuy** [comment]
Vậy để em viết `PKGBUILD` gói `hunspell-vi`

**Comment by NgoHuy** [comment]
Tin vui là `Libreoffice-vi` tích hợp sẵn bộ kiểm tra từ điển

> usr/lib/libreoffice/share/extensions/dict-vi/vi_VN.aff
> usr/lib/libreoffice/share/extensions/dict-vi/vi_VN.dic

**Comment by NgoHuy** [comment]
em đã viết `PKGBUILD` cho  `hunspell-vi`

https://github.com/NgoHuy/buildsystem/commit/ee45b5235ed714991fb090d677c553acbc87bccc

**Comment by Narga** [comment]
Kiểm chính tả hiện giờ kể cả `aspell` hay `hunspell` kiểm tra tiếng việt đều chỉ là ở mức kiểm tra từ đơn viết sai chứ chưa kiểm được về mặt từ ghép, ngữ nghĩa, ngữ pháp. Để làm được thì cần một thuật toán riêng biệt. Trên Windows có một số soft kiểm tiếng việt tuy nhiên đều là các bản thương mại hoặc closed source.
Đây là một trang có tập hợp các tài liệu về tiếng Việt, nếu @NgoHuy làm kiểm chính tả có thể có ích
https://sites.google.com/a/vlcc.edu.vn/vtphong/tai-lieu/chinh-ta

**Comment by icy** [comment]
Cảm ơn @Narga . Việc có một bộ kiểm tra chính tả, ngữ pháp chắc là một chuyện xa vời. Tuy nhiên, trong `hunspell` có cho phép kiểm tra các từ ghép (ví dụ, phải dùng _hoang tàn_ chứ không được viết _hoang tàng_), có thể giải quyết được phần nào bài toán. Nhưng cái này cần nghiên cứu và viết thêm. Việc hỗ trợ từ ghép cho `aspell` thì mình không chắc lắm.
