### ISSUE TITLE
Đọc và kiểm tra lại tài liệu cho uim-vi

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#37]
Anh cần Huy đọc qua và góp ý về tài liệu cho `uim-vi`

http://theslinux.org/doc/uim-vi/

Có nhiều thứ có lẽ là a đã viết quá nhiều thứ không cần thiết :D

**Comment by NgoHuy** [comment]
Anh chia ra hơi nhiều 
phần `Profile` và `vấn đề thường gặp` nên gộp chung.
Mô tả về kiểu gõ nên gộp vào chi tiết kĩ thuật uim.

[OTT]: Phần website nên chỉnh lại cho bề rộng màn hình ra sẽ viết nhiều hơn và thiện cảm muốn đọc hơn

**Comment by icy** [comment]
Profile là cái mô tả các đặc điểm của Profile mặc định, sau này có người phát triển Profile khác thì sẽ tài liệu khác tương ứng, ví dụ `126-uim-vi@foobar`. Phần vấn đề thường gặp chủ yếu mô tả về uim/vi, còn đúng ra phần

   http://theslinux.org/doc/uim-vi/faq/#126

phải nằm trong bài về `126-uim-vi` (đang phân vân có nên chuyển lại không). Phần về `uim` thì chủ yếu liên quan tới cài đặt và cấu hình, không bàn tới kiểu gõ (xtelex, xvni vốn phát triển độc lập không liên quan gì tới `uim` cả.)

E để ý lỗi chính tả a đã đọc thấy khi sáng mà quên note lại giờ tìm không ra :(

Không OT (dài quá)

On Mon, 13 May 2013 08:11:09 -0700
Ngô Huy notifications@github.com wrote:

> Anh chia ra hơi nhiều 
> phần `Profile` và `vấn đề thường gặp` nên gộp chung.
> Mô tả về kiểu gõ nên gộp vào chi tiết kĩ thuật uim.
> 
> [OTT]: Phần website nên chỉnh lại cho bề rộng màn hình ra sẽ viết
> nhiều hơn và thiện cảm muốn đọc hơn 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/TheSLinux/gs/issues/37#issuecomment-17817998

## 

I am ... 5 dog years old.

**Comment by NgoHuy** [comment]
Em vẫn thấy chia ra hỏi nhiều :D

Phần kiểu gõ ta có thể gộp lại `kiểu gõ` + `sử dụng uim` vì nó là một phần của nhau sẽ dễ hơn là chia ra nhiều phần và em đọc có cảm giác vẫn trùng lặp nhiều điểm.

**Comment by icy** [comment]
Để a đọc lại lần cuối, chỉnh lại vài thứ rồi trả lại cho cộng đồng. Bạn nào muốn chỉnh gì thì tạo `pull request` vào trong kho `homepage`. A chỉ muốn tách ra cho dễ điều chỉnh sau này thôi.
