### ISSUE TITLE
Profile switching 

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#38]
Như đã trao đổi trên kênh Irch `#archlinuxvn`, ta cần tìm một phương án chung để đóng gói và triển khai các `profile`, và chuyển qua lại giữa các `profile` tương đối dễ.

Một số `profile` đang chuẩn bị
- e17: https://github.com/TheSLinux/gs/issues/29
- uim-vi: https://github.com/TheSLinux/gs/issues/22 (đã gần xong)
- firefox: https://github.com/TheSLinux/gs/issues/31

Đây là vấn đề lâu dài, đặt ở dòng `G2`.

**Comment by icy** [comment]
Mình sẽ viết sơ phần mô tả cho cái này (dành riêng cho Firefox) và sau đó gửi thông tin lại cho @mrtuxhdb  sau nhé.

**Comment by thuandt** [comment]
:ok:
