### ISSUE TITLE
Web content filtering

### ISSUE THREAD

**Issue by NgoHuy** [TheSLinux/gs#40]
Một vài lý do như `parent control` hoặc kiểm sóat băng thông sẽ cần tới một công cụ lọc nội dung web.

Em đề xuất `dansguardian` :
- Cho phép chặn các website có nội dung người lớn, các site chứa công cụ hack, mã độc,..
- Cho phép tùy chỉnh chặn theo từ khóa, định dạng tập tin, Urls, `regular expression`,...
- Mặc định hợp với nhu cầu cơ bản.

**Comment by icy** [comment]
Đối với cá nhân cái này hơi `overkill`. Trong các trường học hay cơ quan lớn thì nên triển khai ở cách thức khác. Không thấy được lợi ích thật sự của việc dùng lọc này.

**Comment by NgoHuy** [comment]
Em nhận thấy hỗ trợ một gói như vậy trên `TheSLinux` sẽ có ích sau này. Phiên bản `G1` và có thể `G2` chưa hỗ trợ, lợi ích cho việc dùng lọc sẽ tùy vào cá nhân nhưng khi triển khai ở mức rộng hơn sẽ cần thiết.

Em đang tìm hiểu một số gói `privacy` và `secure` như `dnscrypt` hay `tor`, `dansguardian`

**Comment by icy** [comment]
Đối với cá nhân cái này hơi overkill. Trong các trường học hay cơ quan lớn thì nên triển khai ở cách thức khác. Không thấy được lợi ích thật sự của việc dùng lọc này ngoài việc gây khó khăn cho người dùng cá nhân.

**Comment by icy** [comment]
A đặt lại `label` để Huy có thời gian coi thêm.

**Comment by NgoHuy** [comment]
vâng, em sẽ coi thêm :-)

**Comment by xluffy** [comment]
Cá nhân mình thấy gói dansguardian cũng ko cần thiết, đồng ý với anh icy, món này chỉ nên triển khai ở mức doanh nghiệp, cá nhân ko nên tự trói chân mình.

**Comment by icy** [comment]
Có cái này ngon hơn @NgoHuy  nè http://www.privoxy.org/user-manual/filter-file.html

**Comment by NgoHuy** [comment]
em đang dùng privoxy và dansguardian. Có vẻ privoxy đơn lẻ không có tính năng khóa nội dung người lớn anh ah :-D 

Privoxy rất tốt cho lọc nội dung html để làm việc chặn theo từ khóa hehe

**Comment by xluffy** [comment]
Thú thực là khi đọc topic này mình cực tò mò và thắc mắc. Tại sao lại phải tìm cách tự trói chân mình lại, tại sao lại phải chặn web có nội dung người lớn. TheSLinux là một distro hướng tới trẻ em chăng? Bản thân việc cản lọc nội dung trong môi trường enterprise là do ý thức của nhân viên, và để bảo vệ các dữ liệu và hệ thống quan trọng. Việc một cá nhân muốn xem gì kể cả nội dung người lớn ở nhà họ mình thấy chả có gì mà cản lọc cả.

**Comment by NgoHuy** [comment]
tùy mỗi người nghĩ thôi, máy tính nếu chỉ có 1 người dùng thì sẽ không có gì, nếu muốn giới hạn tải tập tin và giới hạn định dạng tải tập tin, hay gì gì đó để tiết kiệm băng thông,... thì cần một công cụ nào đó. 
Anh không dùng và em muốn đề xuất hỗ trợ đâu phải bắt cài mà nhỉ haha

**Comment by icy** [comment]
A chỉ muốn tiếp tục hướng tới đề tài này bởi vì Huy đã
gợi ý , nên a muốn tiếp tục phát triển xem có ra được gì.
Còn chuyện khóa, thì như a đã nói làm ở mức thấp hơn tí
sẽ hiệu quả và đơn giản hơn.

On Fri, 24 May 2013 06:19:11 -0700
Ngô Huy notifications@github.com wrote:

> tùy mỗi người nghĩ thôi, máy tính nếu chỉ có 1 người dùng thì sẽ
> không có gì, nếu muốn giới hạn tải tập tin và giới hạn định dạng tải
> tập tin, hay gì gì đó để tiết kiệm băng thông,... thì cần một công cụ
> nào đó. Anh không dùng và em muốn đề xuất hỗ trợ đâu phải bắt cài mà
> nhỉ haha
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/TheSLinux/gs/issues/40#issuecomment-18404162

## 

I am ... 5 dog years old.
