### ISSUE TITLE
Kịch bản tạo file `.iso`

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#41]
Huy đặt các kịch bản tạo file `.iso` cùng với các chỉ dẫn trên kho tạm nào đó để a đưa vào `theslinux-forlks`. Quá trình tạo file `.iso` sẽ được tự động hóa và sẽ làm từ máy `phantom3`

**Comment by NgoHuy** [comment]
Hiện tại em vẫn dùng `arch iso` và chưa tạo ra kịch bản hòan chỉnh nào

**Comment by icy** [comment]
@NgoHuy  xem lại nhé http://www.mail-archive.com/hackers@lists.theslinux.org/msg00000.html
