### ISSUE TITLE
TheSLinux default terminal

### ISSUE THREAD

**Issue by NgoHuy** [TheSLinux/gs#43]
Em đề nghị dùng `tilda` thay cho `uxrvt` vì 
- Linh động trong chỉnh sửa
- Không nặng nề như `gnome-terminal`
- Thân thiện với người dùng mới

**Comment by icy** [comment]
mất session lấy lại được không em?

**Comment by NgoHuy** [comment]
em chưa hiểu ý anh lắm

**Comment by icy** [comment]
Các `terminal` mà e đề cập khi bị tắt đi (vô tình  hay cố ý) thì thông tin về các phiên làm việc sẽ mất. Đã dùng tới `terminal` thì cách tốt nhất là nên dùng kèm với `tmux` hoặc `screen`. Vấn đề là e có thể chuẩn bị một tài liệu thật tốt, đơn giản, với các thiết lập mặc định của `tmux` (hay `screen`) cho người dùng. Sử dụng `tmux` không phải là vấn đề, vì những người dùng `shell` hay `terminal` thường có khả năng nhất định để hiểu nó là gì . Còn các bạn `newbie` thì không cần dùng cái đó, chỉ cần bận `xterm` và `urxvt` lên là xong thôi mà =)

**Comment by icy** [comment]
TODO:
- viết tài liệu dùng (cơ bản) `urxvt` (bật, tắt, sao , chép,...)
- viết tài liệu dùng (cơ bản) `tmux` (với các thiết lập mặc định của `tmux`)

**Comment by thuandt** [comment]
Phần viết tài liệu dùng cơ bản về tmux em sẽ đảm nhận. Nhưng em chưa rõ sẽ viết document như nào. Có template gì không ạ?

**Comment by icy** [comment]
@mrtuxhdb Mình dùng `nanoc`, em có thể `fork` kho này ra https://github.com/TheSLinux/homepage rồi viết . Hiện chưa có tài liệu để viết, nhưng hầu hết các ý có thể lấy từ trang `Author Guide` của nhóm ArchLinuxVn http://archlinuxvn.org/vn/author-guide/ . 

Các bài viết ví dụ: https://github.com/TheSLinux/homepage/tree/master/content/doc

Khi nào viết ổn thì tạo `pull request`. Khi nào quen mình sẽ cấp quyền ghi thẳng vào kho chính.

**Comment by thuandt** [comment]
OK anh :)

**Comment by icy** [comment]
Chú ý các vấn đề của _n0bawk_ khi dùng `emacs` (`vi`) với `urxvt`.

**Comment by NgoHuy** [comment]
Cụ thể là vấn đề thế nào vậy anh ?

**Comment by thuandt** [comment]
Trước giờ em thay nhiều `terminal emulator` rồi nhưng sau chốt thì vẫn dùng `gnome-terminal` hoặc `lxterminal`.

**Comment by icy** [comment]
Nếu mà lựa chọn thì sẽ rất nhiều khả năng, gây tranh cãi cả ngày ấy chứ. Mình chỉ cần chọn một cái có thể sống "lâu" nhất, làm việc ở nhiều môi trường nhất có thể. Với `tmux` và `screen` thì có thể dùng ở cả máy cá nhân và trên các máy ở xa (`remote`), còn các công cụ đồ họa là hỗ trợ. (`xterm`, `lxterminal`, là để mồi; tất nhiên chúng có các ưu thế riêng).

Nếu có đông thành viên mình sẽ làm phần `vote` giống cách làm `RFC` của đội phát triển `PHP` nhỉ :)

**Comment by icy** [comment]
Dùng profile không cần quan tâm cái này.
