### ISSUE TITLE
Thử nghiệm WindowMaker

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#44]
Xem nó có gì hay so với E17 =)

**Comment by NgoHuy** [comment]
- Ấn tượng đầu `xấu thê thảm`
- `Windowmaker` tương đối nhẹ so với `E17` có config trực quan
- File config là text
- Tự động thay `xinitrc` khi cài

**Comment by icy** [comment]
On Sun, 02 Jun 2013 19:49:59 -0700
Ngô Huy notifications@github.com wrote:

> - Ấn tượng đầu `xấu thê thảm`
> - `Windowmaker` tương đối nhẹ so với `E17` có config trực quan
> - File config là text
> - Tự động thay `xinitrc` khi cài

hehe vấn đề là cái `feature` của nó ổn định cả chục năm rồi đó em :D

## 

I am ... 5 dog years old.

**Comment by icy** [comment]
thay KDE lên KDe4 bà con bỏ chạy một số. Từ GNOME qua GNOMe3 cũng gây nhiều tranh cãi. Về các tính năng cơ bản thì `WM` còn hay hơn cả `XFCE4`, còn cách bố trí và tiếp cận thì khác với `e17`. Nói chung nên xem cho biết.

Do `Wm` không nhớ được vị trí và kích cỡ cửa sổ nên hiện a vẫn dùng `e17` hehe

**Comment by NgoHuy** [comment]
nhìn giống `windows XP` -_-

**Comment by icy** [comment]
On Sun, 02 Jun 2013 20:16:28 -0700
Ngô Huy notifications@github.com wrote:

> nhìn giống `windows XP` -_-

Anh cần một môi trường `stable`, ít thay đổi để không yêu cầu
thay đổi `user experience`, điều này rất quan trọng đó em. Nếu xem
lại cái `e17 profile` thì a có nói tới yêu cầu này. `WindowsXP`
rất đáng học hỏi về thiết kế đó.

Ba cái lăn tăn khác không quan trọng. Ngoài ra nếu em biết dùng
thì `wm` nó đẹp đó ha. Đừng vội nhận xét nó. Xem lại ý tưởng
thiết kế của nó đi.

**Comment by NgoHuy** [comment]
Đó mới là nhận xét ban đầu thôi anh, em chưa đi sâu vào thiết lập để tạo `profile` :-P

**Comment by icy** [comment]
http://article.gmane.org/gmane.compw.window-managers.windowmaker.devel/6093

**Comment by icy** [comment]
Cái này dời qua `G2`. Điểm rất dở của `wm` là `docking` của nó chiếm và sinh ra quá nhiều không gian thừa không cần thiết trên màn hình, nhìn vừa thiếu vừa thừa rất khó chịu. Tính năng ghi nhớ vị trí và kích cỡ cũng không thấy đâu.

Nếu có điều kiện cố thể ngó qua và điều chỉnh lại mã nguồn :)

**Comment by NgoHuy** [comment]
`docking` và `terminal` hehe

**Comment by icy** [comment]
`terminal` thì liên quan gì đâu vẫn như các `apps` khác mà

**Comment by icy** [comment]
Khi nào `wm` có hỗ trợ khả năng nhớ các kích cỡ và vị trí các cửa sổ thì sẽ xem xét cho vào hệ thống.

**Comment by icy** [comment]
Trong bài này http://article.gmane.org/gmane.compw.window-managers.windowmaker.devel/6192 có gợi ý là dùng tính năng `lưu session` của `wm` để lưu vị trí và kích thước các cửa sổ

**Comment by icy** [comment]
`windowmaker` còn phải cải tiến nhiều :)
