### ISSUE TITLE
Bổ sung tính năng gõ ngôn ngữ Latex cho Libreoffice

### ISSUE THREAD

**Issue by minhhieu** [TheSLinux/gs#46]
Mặc dù Libreoffice có chức năng gõ công thức toán nhưng quá phức tạp.Kỳ Anh nên nghiên cứu phần mềm tích hợp vào bộ office này gõ giống như ngôn ngữ Tex mà mathtype đã tích hợp vào word.

**Comment by icy** [comment]
Hiếu coi dùng `Lyx` hoặc dùng `LaTeX` luôn nhé.

**Comment by minhhieu** [comment]
Ý của Hiếu là không cần dùng Win nữa mà vẫn đáp ứng được việc soạn đề gởi cho những người không biết về Tex kìa. Và lôi luôn những người dùng win về với chúng ta luôn. Nếu bạn cảm thấy việc này khó khăn thì bỏ qua

**Comment by icy** [comment]
Bảo Hiếu dùng `Lyx` chớ có bảo Hiếu dùng `Windows` đâu?
