### ISSUE TITLE
pkgbuild cho linux-backports

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#48]

**Comment by icy** [comment]
Status: New idea in low priority, Put in BackLog no-one takes care. An not-important feature request

**Comment by NgoHuy** [comment]
em thấy có cái này trên AUR, ta có thể viết lại theo được 

https://aur.archlinux.org/packages/backports-patched/

**Comment by icy** [comment]
On Thu, 12 Sep 2013 03:50:39 -0700
Ngô Huy notifications@github.com wrote:

> em thấy có cái này trên AUR, ta có thể viết lại theo được 
> 
> https://aur.archlinux.org/packages/backports-patched/

Tạm thời bỏ qua chú backports này, không có thời gian :D

**Comment by icy** [comment]
Change G1 => G2

**Comment by icy** [comment]
=> won't fix
