### ISSUE TITLE
Thử nghiệm Anything-Sync-Daemon

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#49]
- Source: https://github.com/graysky2/anything-sync-daemon
- Link: https://wiki.archlinux.org/index.php/Anything-sync-daemon

**Comment by icy** [comment]
Đây là tính năng có ích với người dùng thẻ nhớ.

**Comment by icy** [comment]
Gán lại cho @NgoHuy . Sẽ thử nghiệm trên phant6m2

**Comment by thuandt** [comment]
Thử nghiệm cái này là thử nghiệm như nào hả anh @icy ?
Cái này hữu ích với con SSD của em :)

**Comment by icy** [comment]
@thuandt Dùng thử để biết cách cấu hình, cách thêm bớt, ... @NgoHuy  đang chuẩn bị thử thì bão tới, cúp điện, giờ máy vẫn chưa có mà thử :)
