### ISSUE TITLE
Tạo archive cho các nhóm thư ở mail-archive.com

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#52]
Xem thêm http://www.mail-archive.com/faq.html#newlist

**Comment by icy** [comment]
```
From: FreeLists Mailing List Manager <ecartis@freelists.org>
To: xkyanh@********
Subject: Ecartis command results: No commands found
Date: Fri, 14 Jun 2013 18:03:21 -0400 (EDT)

>> subscribe archive@mail-archive.com  
User fails blacklist check.
```

**Comment by icy** [comment]
Vẫn còn vài trở ngại với http://freelists.org/

**Comment by thuandt** [comment]
Hệ thống mailing list của `theslinux` khó đăng kí và sử dụng.
Cứ dùng kiểu như github này còn hay hơn

**Comment by icy** [comment]
Mình sẽ có máy chủ mail riêng trong thời gian tới, nên tạm thời các list vẫn dùng như vậy (dịch vụ của `freelists.org`)

Thuận có thể quản lý email server không, kiểu cái này #58 ? Có bạn nào có khả năng thì giới thiệu nhé.
