### ISSUE TITLE
Chuẩn bị tài liệu cho developer

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#54]
1. -Tài liệu về git-
2. Tài liệu về coding style
3. Tài liệu về cách dùng và quản lý các nhóm thư
4. Tài liệu về cách thức trao đổi, báo lỗi trên github, nhóm thư, ...
5. Tài liệu về những việc cần làm với thứ tự ưu tiên
6. Giấy phép và các quyền lợi, trách nhiệm liên quan

**Comment by icy** [comment]
Tài liệu về cách thêm tin tức, sự kiện mới vào trang chủ: http://theslinux.org/doc/homepage/add_new_event/ . @xluffy

**Comment by icy** [comment]
Lớp hướng dẫn dùng Git vào tháng 6/2013: http://theslinux.org/events/2013/06-git-training/

**Comment by icy** [comment]
Chú ý về cách sử dụng và thông tin cung cấp bởi hệ thống `ticket` trên `Github`: Khi thay đổi các nhãn sẽ không còn thông tin về thời gian. Tạm khắc phục bằng cách sử dụng các `comment` để theo dõi.

**Comment by icy** [comment]
Xem thêm #75

**Comment by icy** [comment]
Working on this

**Comment by ck196** [comment]
anh icy up slide về training Git lên trang chủ cho mọi người đi ạ.

**Comment by icy** [comment]
Do phong cách viết `slide` của anh không giống ai, nên có lẽ anh sẽ chia sẻ về cách dùng `git` trong các tài liệu riêng, chứ không thông qua `slide` được. Stay tuned!

**Comment by icy** [comment]
CC: @lokiheero  @vanhonit 

Chỉ dẫn dành cho `sysadmin`: http://theslinux.org/devs/guidelines/sysadmin/

**Comment by icy** [comment]
@monkeykju Có vài quy tắc cơ bản, xài tạm http://theslinux.org/doc/git/basic_rules/ :)
