### ISSUE TITLE
Đóng gói cho zuluscript 

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#55]
http://code.google.com/p/zulucrypt/

**Comment by NgoHuy** [comment]
Hiện gói đã có trên `AUR` gói này cần một bạn duy trì gói

> https://aur.archlinux.org/packages/zulucrypt/

**Comment by icy** [comment]
Ủa rứa lúc này tìm không ra :) nếu có rồi thì để a đẩy vào kho `buildsystem`.

**Comment by NgoHuy** [comment]
có thể đóng `issue` được chưa anh :)

**Comment by icy** [comment]
Còn ở `backlog` em. Khi nào đã có `commit` vào hệ `bs` mới đóng. Chuyện đóng mở này này em không cần log.

**Comment by icy** [comment]
@sokomo  Phối hợp với @NgoHuy  để đóng gói theo định dạng của #theslinux.  Việc đóng gói ở ưu tiên thấp.
