### ISSUE TITLE
Tài liệu hướng dẫn đăng ký vào nhóm thư

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#57]
Hiện cách đăng ký vào các nhóm thư khá phức tạp và không quen thuộc với người dùng Google. Cần đưa ra các hỗ trợ đơn giản hơn, tài liệu chi tiết hoặc kênh hỗ trợ nhanh hơn.

**Comment by xluffy** [comment]
Chà, không rõ em có hiểu nhầm ý anh ko ta, em thấy việc đăng ký cũng khá dễ dàng mà.

**Comment by NgoHuy** [comment]
Khó khăn khi đăng bài, hay yêu cầu `moderator` xác nhận nhưng em không tìm ra cách xác nhận

**Comment by icy** [comment]
Vừa rồi có một số email đăng ký đẩy ngược về email của anh, và dường như sau đó người dùng không đăng ký được luôn. Hệ thống của `freelists` rất mạnh ở các dòng lệnh qua email, nhưng hơi khó gặm vì nó chẳng để liên kết nào để thay thế lệnh cả.

Nhiều phần hướng dẫn có thể làm ngắn lại. Có điều kiện a sẽ giới thiệu với các bạn nhiều hơn. Tạm thời để cái này đây đã.

**Comment by ghost** [comment]
em đăng ký nhóm thư tới 2 lần mà không được. sao không dùng nhóm thư của gmail anh icy?

**Comment by icy** [comment]
@xclarke  dùng cái này thử chưa em http://theslinux.org/lists/#fastoption ? Nó sẽ gửi email và em theo hướng dẫn làm theo thôi. Không dùng nhóm thư google do một số bất tiện.

**Comment by icy** [comment]
High -> Low priority

**Comment by icy** [comment]
Đổi chủ đề: Hỗ trợ đăng ký nhóm thư thân thiện hơn => Tài liệu hướng dẫn đăng ký vào nhóm thư.

Trong tương lai sẽ chỉ sử dụng giao diện dòng lệnh qua thư để đăng ký tham gia, rời bỏ nhóm thư.

**Comment by NgoHuy** [comment]
cụ thể nhóm thư nào anh ? nếu mọi nhóm thì e không tiện cho người dùng lắm

**Comment by icy** [comment]
Tất cả các nhóm thư. Tài nguyên hệ thống và con người không đủ để quản lý các trang web đâu em. Việc sử dụng email thật ra rất tiện và nhanh hơn nhiều so với cách dùng trang web. Chỉ là do ... thói quen thôi.

**Comment by icy** [comment]
Đã xong. Xem thêm ở #58 và http://theslinux.org/lists/ (http://theslinux.org/lists/en/)
