### ISSUE TITLE
Cài đặt mailing list

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#58]
- Cài đặt trình quản lý `mailing list`
- Cài đặt một số `cron job` để tạo `arhive` cho một số dự án

**Comment by icy** [comment]
Chi tiết cài đặt `Mailman` và `exim4` cùng nhau http://www.exim.org/howto/mailman21.html

**Comment by icy** [comment]
Xem thêm https://github.com/Exim/exim/wiki/MailmanConfiguration

**Comment by icy** [comment]
@vanhonit coi tài liệu trong liên kết trên, cài đặt thử nghiệm (nếu cần máy chủ thì mình có thể cung cấp theo giờ), sau đó chuẩn bị tài liệu (viết theo định dạng `markdown` hoặc `kramdown`). Mình sẽ có khoảng 3 server sử dụng chung cấu hình này. 

Sau khi có tài liệu và các chỉ dẫn cần thiết, sẽ có một bạn chuyên làm để chuyển vào `puppet`.

**Comment by vanhonit** [comment]
Okay ! Có gì cho mình mượn server vào buổi tối để thử !

**Comment by icy** [comment]
@vanhonit Cách làm việc là thế này
1. Bạn kiểm tra lại các cấu hình trên máy ảo
2. Ghi chú các tài liệu và chuẩn bị các tài liệu cần thiết
3. Nếu được, chuẩn bị một kịch bản cài đặt tự động viết bằng `#bash`. Ví dụ, với `exim4` hoàn toàn có thể dùng cấu hình của máy này cho máy khác, nhưng chỉ phải thay đổi các thông tin về `hostname` chẳng hạn
4. Các tài liệu và kịch bản cài đặt sẽ được xem qua (review) và xác nhận bởi các thành viên trong nhóm
5. Chuyển kịch bản cài đặt vào hệ thống `puppet`
6. Triển khai trên máy thật

Hiện giờ, do server bật lên phải tốn tiền (:D) nên hạn chế dùng server thật. Mình sẽ cung cấp các máy khi bạn thật sự cần. (Mình sẽ xin thêm các máy để các bạn thử nghiệm hệ thống. Stay tune!)

**Comment by vanhonit** [comment]
Cho mình biết server đang sử dụng distro nào vậy ?

**Comment by icy** [comment]
Khi tối mình trả lời rồi mà sau không lên được?

Server đang dùng là `Debian 7`. Một số con dùng `Arch`. Cấu hình của `exim4` và `mailman` thường giống nhau, có thể dùng chung giữa các máy sau một số thay đổi cơ bản.

**Comment by vanhonit** [comment]
Ok ! Để mình cài máy ảo giống cùng distro luôn cho dễ.

**Comment by icy** [comment]
Mình mới viết xong, @vanhonit  xem qua có gì góp ý nhé http://theslinux.org/devs/guidelines/sysadmin/

**Comment by vanhonit** [comment]
@icy và mọi người thông cảm hiện giờ đang xài mạng FPT không biết bị vấn đề gì không thể truy cập hay download từ nước ngoài nên tốc độ làm việc hơi chậm. Chắc phải đợi vài hôm nữa xem khả quan hơn ko ? Giờ lên github mà còn phải lên bằng fakeip.org nữa.

**Comment by vanhonit** [comment]
Mình tìm được link này hướng dẫn khá chi tiết về cài đặt EXIM4 http://www.unixmen.com/howto-install-exim4-mail-server-in-ubuntu-and-linuxmint/

**Comment by icy** [comment]
@vanhonit  Cứ thong thả, cần hỗ trợ gì thì kêu mọi người (có thể nói trên nhóm thư `hacker`), ví dụ về đường mạng, bla bla. Chỉ cần `update` tiến độ đều đặn để mọi người biết tiện theo dõi thôi.

Cần cài đặt `exim4` thì cần chú ý cài đặt `hostname` máy cho đúng đã (chạy `hostname` và `hostname -f` để xem), sau đó chạy `dpkg-reconfigure exim4-config` rồi làm theo hướng dẫn là được rồi. Cấu hình sinh ra có thể dùng ở nhiều nơi đó. Sau khi cài đặt xong thì có thể thử gửi email ra ngoài xem được không, và gửi email từ một máy nội bộ vào máy đó xem được không.

Phần khó khăn là tạo và kết hợp `mailman` với `exim4`, mình đã gửi liên kết ở trên.

**Comment by thuandt** [comment]
Sao không dùng postfix mà dùng exim hả anh @icy

**Comment by icy** [comment]
@mrtuxhdb  A dùng nhiều thứ thấy về cách tiếp cận từ phía `sysadmin` thì `exim4` đơn giản và tiện lợi hơi nhiều. Sẽ còn dùng `exim4` cho nhiều việc khác nữa nên bây giờ chọn luôn. Việc tích hợp `mailman` với `postfix` hay `exim4` thì cũng khó ngang nhau.

@mrtuxhdb có cao kiến gì không?

**Comment by icy** [comment]
Cấu hình cho `exim4` trên hệ thống `Debian` thật ra rất đơn giản, chỉ việc chạy theo cái `wizard` (nhờ lệnh mình đã chỉ ra ở trên) là xong thôi. Có thể chọn `split-configuration` để tiện chỉnh sửa sau này.

**Comment by thuandt** [comment]
Hệ thống work là được, cũng không quan trọng lắm. Em chưa setup mailman bao giờ nên không dám khẳng định gì :)

**Comment by vanhonit** [comment]
Tình hình là mình cấu hình y như hướng dẫn mà mail gửi không đi. Thử bằng câu lệnh echo “This is test mail from my machine .” | mail -s Testing honnguyen@honnguyen.com không được, thử bằng exim -v honnguyen@honnguyen.com cũng không luôn.

**Comment by icy** [comment]
@vanhonit Dùng lệnh `sendmail -bt foobar@example.com` để kiểm tra xem, sau đó kiểm tra `log` của hệ thống email. Nếu bị lỗi do bị chặn thì mình sẽ có hướng kiểm tra khác.

**Comment by vanhonit** [comment]
Mail gửi ra gmail được rồi có xem là thành công chưa nhỉ ? Hôm qua gửi mà hôm nay mail nó mới đến không hiểu nổi !

**Comment by icy** [comment]
Kiểm tra log trong `/var/log/exim4` nhé @vanhonit . Mail vào, mail ra. Không cần phải kiểm tra ở mức `internet` đâu, chỉ cần kiểm tra ở các máy `local` là tốt rồi, vì ra ngoài có khi bị chặn bởi các hệ thống `spam` nữa đó :D 

Cấu hình `exim4` xong thì tới phần `mailman` nhé :D 

Từ từ làm, hy vọng là @vanhonit  học thêm được nhiều điều mới :D

**Comment by vanhonit** [comment]
log thì báo thành công ! Vấn đề mình gặp là gửi trong local cũng báo thì không nó không hiểu domain mặc dù đã thử add domain vô hosts files. rồi thử tạo files /etc/mailip luôn rồi ! Gửi bằng ip thì nó bị lỗi !

**Comment by icy** [comment]
Có gì trao đổi thêm trên kênh `irc` sẽ tiện hơn và nhanh hơn nhé @vanhonit

**Comment by icy** [comment]
Priority Low -> High

**Comment by vanhonit** [comment]
- Mình làm theo hướng dẫn ở đây http://www.debian-administration.org/article/617/Mailman_and_Exim4 và kết quả như thế này
  ![mailman](https://f.cloud.github.com/assets/1215676/824009/e539b85c-f02e-11e2-8b9c-4643801a63af.png) không biết được chưa ? Nào giờ mình chưa từng sử dụng và cấu hình cái này nên không rõ sử dụng như thế nào.

**Comment by vanhonit** [comment]
- Khi nào có thể gì @icy cho mình thông tin host để mình cài đặt thử.

**Comment by icy** [comment]
Minh sẽ cung cấp thông tin  lại sớm. @vanhonit có hay lên kênh #irc mình trao đổi dễ hơn nhé. !

**Comment by icy** [comment]
Hi @vanhonit , khi nào bạn có thể gặp trên kênh `irc` được. Một số bạn cũng sẽ tham gia vào việc này, nên cần trao đổi nhiều hơn trước khi triển khai thực tế. Cảm ơn @vanhonit

**Comment by vanhonit** [comment]
Mình lên irc hoài mà không gặp ai hết !

**Comment by icy** [comment]
(đang trao đổi với @vanhonit  trên #irc)

**Comment by icy** [comment]
Có tiến triển gì không @vanhonit . Lâu ngày không thấy bạn online. Chúc khỏe :)

**Comment by icy** [comment]
Đổi chủ đề: Cài đặt và quản lý l00s4r => Cài đặt mailing list

**Comment by vanhonit** [comment]
Có mấy lần lên mà không thấy @icy online. Tình hình là thời gian qua bận 1 số việc cá nhân nên không triển khai được gì thêm. Sorry anh em !

**Comment by icy** [comment]
Không sao. Chắc lên trễ quá nên không gặp mình thôi đấy @vanhonit . Khi nào rảnh thì tham gia tiếp nhé. Nhớ update cho mọi người biết (update ở đây hoặc nhóm thư bla bla)

**Comment by vanhonit** [comment]
rất xinh lỗi về sự chậm trễ của mình ! Chắc trong khoảng 1-2tháng tới không tham gia đóng góp được gì rồi. Hy vọng sau đó sẽ tiếp tục được.

**Comment by icy** [comment]
Không vấn đề gì @vanhonit . Khi nào bạn có thời gian thì tham gia thôi :)

**Comment by icy** [comment]
status -> Testing

**Comment by icy** [comment]
CC: @TheSLinux/developers 

Đang thử nghiệm hệ thống mailing list mới. Các bạn có thể thử cho mình biết nhé. Cảm ơn các bạn.

**Comment by icy** [comment]
- Đã đặt toàn bộ cấu hình hệ thống email vào puppet
- Nhóm thư mới _questions at domain_. Để đăng ký, gửi thư tới _ecartis at domain_ với chủ đề là _subscribe questions_. Thay _domain_ bằng _lists.theslinux.org_

**Comment by ck196** [comment]
```
                                                                                                                                                                                                                                                                      Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                        From: Ky-Anh HuynhSent: Sunday, 8 September 2013 22:29To: TheSLinux/gsReply To: TheSLinux/gsCc: monkeykjuSubject: Re: [gs] Cài đặt mailing list (#58)Đã đặt toàn bộ cấu hình hệ thống email vào puppet
```

Nhóm thư mới questions at domain. Để đăng ký, gửi thư tới ecartis at domain với chủ để là subscribe questions. Thay domain bằng lists.theslinux.org

—Reply to this email directly or view it on GitHub.

**Comment by icy** [comment]
Sao thư trống trơn vậy @monkeykju ?

**Comment by icy** [comment]
CC: @TheSLinux/developers 

Đã xong, mừng quá trời :) Các việc tiếp theo
- Thông báo, và chuyển qua nhóm thư mới (XONG)
- Cập nhật tài liệu trên trang chủ (XONG)
- Đặt các archiver vào nhóm thư mới (ĐANG)
- Cài đặt chế độ sao lưu cho hệ thống nhóm thư
- Đặt các cấu hình và thông tin vào git repository

Bạn nào có thể giúp mình không?

**Comment by icy** [comment]
@xluffy  hay @NgoHuy  kiểm tra mình tính năng digest nhé. Thanks.

**Comment by icy** [comment]
Tạm gán lại (@icy => @xluffy )

**Comment by icy** [comment]
Gán lại cho @icy
