### ISSUE TITLE
TODO for G1

### ISSUE THREAD

**Issue by NgoHuy** [TheSLinux/gs#6]
- Packages list
- EFI: support i686 or x64
- Configure file for E17, bashrc, profile, ibus.
- dd or other method makes usb/cd image.

**Comment by icy** [comment]
On Wed, 06 Mar 2013 06:18:11 -0800
Ngô Huy notifications@github.com wrote:

> - Packages list
> - EFI: support i686 or x64
> - Configure file for E17, bashrc, profile, ibus.
> - dd or other method makes usb/cd image.

Em có thể dùng phần wiki của github để sọan phần TODO, tuy nhiên TODO
này có tính cá nhân nhiều hơn. Hệ thống ticket thì dùng để đưa ra các
vấn đề cụ thể cần giải quyết, và _không nên gộp chung_ nhiều cái vào
một chủ để thế này (off-topic)

## 

I am ... 5 dog years old.

**Comment by icy** [comment]
Dùng wiki thay vì ticket system Huy nhé.
