### ISSUE TITLE
Tìm hiểu về cách gõ tốc ký và phương án hỗ trợ trong uim

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#61]
Các bộ phận gõ tốc ký thường có những quy tắc gõ riêng, liệu có thể hỗ trợ các quy tắc này không? Và trước mắt, các quy tắc này có thể tìm thấy ở đâu?

CC: @NgoHuy  @xluffy  @mrtuxhdb @lewtds

**Comment by lewtds** [comment]
Em google sơ sơ thì không thấy. Có lẽ đơn giản nhất là đi hỏi một cách lịch sự. Chắc người ta cũng không có vấn đề gì mà không chia sẻ cho mình đâu.

**Comment by icy** [comment]
Mình đặt vấn đề này vì hồi xưa mình có nghe nói có các hỗ trợ gõ tốc ký và các kiểu tương tự. Đi tìm mà cũng không thấy :D Cái này chắc cũng phải là kinh nghiệm và khoa học.

Trên mạng tìm cũng thấy có một số bác đề xuất kiểu gõ tốc ký, mà cách gõ nhìn quá phức tạp và với người đã bắt đầu từ lâu như mình khó mà học lại.

**Comment by xluffy** [comment]
Em thấy tốc ký thì mấy cha nhà báo hay xài vì phỏng vấn nói nhanh, mền dư thời gian cứ thong thả gõ :v:

**Comment by icy** [comment]
Haha, anh muốn có hỗ trợ cho cánh nhà báo đó em :D Anh cũng quen vài người làm phóng viên, để a hỏi họ xem thử.
