### ISSUE TITLE
Tạo githook gửi email thông báo khi có commit vào các kho chính

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#62]
Khi có thành viên `commit` vào trong các kho của dự án, một email sẽ được gửi để thông báo đến các thành viên (có thể dùng nhóm thư `phantom`) biết và kiểm tra khi cần thiết.

Chủ để của thư thông báo cần phải có các thông tin cơ bản
- Tên dự án, tên khoa
- Tên tác giả (cuối cùng)
- Dòng chủ đề của (của `commit` cuối cùng)

Nội dung thư phải / nên gồm các thay đổi mới nhất _(so với lần cuối)_

**Comment by icy** [comment]
Xem thêm https://github.com/git/git/blob/master/contrib/hooks/post-receive-email

**Comment by lewtds** [comment]
Cái này hình như mỗi repo lại một hook thì phải bác ah @@

**Comment by icy** [comment]
Đúng rồi @lewtds . Hiện giờ mình xài `hook` riêng, không có tính năng phát sinh và gửi email như trong cái liên kết ở trên. Việc có `hook` này là cần thiết để biết các thay đổi đang diễn ra. Việc dùng hệ thống theo dõi của `github` chỉ là một phần, còn kho chính thì mình chạy trên máy chủ riêng.

**Comment by icy** [comment]
Các `hook` có thể dùng sẵn , và sẽ làm sau khi hoàn thành #58

**Comment by icy** [comment]
Xem thêm: #58, #86

Đã làm xong. Chủ đề này không nên đóng lại quá sớm thế này ;)
- Xem kho lưu trữ http://news.gmane.org/gmane.linux.distributions.theslinux.phantom
- Hook: https://github.com/TheSLinux/homepage/blob/core/bin/git.hook.post-receive-email.sh
