### ISSUE TITLE
l00s5r: nâng cấp hệ thống Debian 6 -> Debian 7

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#67]

**Comment by icy** [comment]
## Nội dung tập tin /etc/apt/sources.list

```
#
# Purpose: New configuration: Upgrade to Debian 7
# Date:    2013 July 2nd
# Author:  Anh K. Huynh
#
deb http://mirrors.kernel.org/debian/ wheezy main
#deb-src http://mirrors.kernel.org/debian/ wheezy main

deb http://security.debian.org/ wheezy/updates main
#deb-src http://security.debian.org/ wheezy/updates main

# wheezy-updates, previously known as 'volatile'
deb http://mirrors.kernel.org/debian/ wheezy-updates main
#deb-src http://mirrors.kernel.org/debian/ wheezy-updates main
```

## Các lệnh cần thiết

```
# pacman -Syv
# pacman -Suv
# apt-get dist-upgrade
# reboot
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.1 (wheezy)
Release:        7.1
Codename:       wheezy
```

**Comment by thuandt** [comment]
Lỗi typos anh @icy ơi.
`dist-upgrade` chứ không phải `distr-upgrade`

**Comment by lewtds** [comment]
Hở, sao trong cùng hệ thống lại lai được pacman và apt hả anh?

**Comment by thuandt** [comment]
@lewtds nó là package manager thôi mà. Có source thì cài ở đâu chẳng được :3

**Comment by lewtds** [comment]
Nhưng mà dùng 2 cái một lúc thì nó quản lý file ntn anh? conflict thì sao? `pacman` có chơi được với deb package không?

**Comment by icy** [comment]
@mrtuxhdb Cảm ơn e, anh đã chỉnh lại lỗi.
@lewtds http://github.com/icy/pacapt dùng mọi lúc mọi nơi, riêng cái `dist-upgrade` thì chịu chết :D

**Comment by icy** [comment]
Server này do một cty tài trợ, dùng để quản lý nhóm thư, xem thêm ở http://theslinux.org/l00s/5r/

**Comment by lewtds** [comment]
Thanks bác @icy, hóa ra đây không phải pacman mà chỉ là một wrapper. :D

**Comment by icy** [comment]
haha, mình phải làm việc với rất nhiều `distro` khác nhau, nên tiện tay viết luôn cái đó. Mỗi cái mỗi nhớ rất là phiền đấy : ^^
