### ISSUE TITLE
Chậm mởi kết nối tới Mirror (FPT)

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#68]
Rất khó mở một kết nối mới tới trang http://mirror-fpt-telecom.fpt.net/theslinux/ , vì một số lý do nào đó mà phải chờ rất lâu, thậm chí có khi kết quả trả về là ... không có gì. Khi đã mở được kết nối rồi thì lại truy xuất hơn, không có vấn đề gì về tốc độ tải tập tin xuống.

**Comment by icy** [comment]
Khi `client` mở kết nối tới máy chủ của `FPT`,  mã trả về (HTTP return code) là `0`, không hợp lệ (đúng là một trong các mã thông thường như `200`, `301`, `404`. Xem thêm [1]). Do mã trả về không đúng, nên trình duyệt sẽ tiếp tục chờ đợi mã trả về hợp lệ, khiến cho thời gian chờ đợi tăng lên cho đến khi `timeout`. Một số trường hợp khi dùng qua `squid`, sẽ thấy nội dung trả về trước, nhưng mà `squid` vẫn chờ đợi mã trả về hợp lệ.

[1] http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

```
$ curl -L http://mirror-fpt-telecom.fpt.net/theslinux/ -vI
* Adding handle: conn: 0x2526d80
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x2526d80) send_pipe: 1, recv_pipe: 0
* About to connect() to mirror-fpt-telecom.fpt.net port 80 (#0)
*   Trying 118.69.250.132...
* Connected to mirror-fpt-telecom.fpt.net (118.69.250.132) port 80 (#0)
> HEAD /theslinux/ HTTP/1.1
> User-Agent: curl/7.30.0
> Host: mirror-fpt-telecom.fpt.net
> Accept: */*
> 
< HTTP/1.1 000
HTTP/1.1 000
* Server nginx is not blacklisted
< Server: nginx
Server: nginx
< Date: Wed, 10 Jul 2013 04:15:55 GMT
Date: Wed, 10 Jul 2013 04:15:55 GMT
< Content-Type: text/html
Content-Type: text/html
< Connection: keep-alive
Connection: keep-alive

< 
* Connection #0 to host mirror-fpt-telecom.fpt.net left intact
```

**Comment by trung-ng** [comment]
Đã xử lý xong

Lỗi ngx-fancyindex module

Solution: Rebuild nginx với cách fix lỗi ngx-fancyindex từ đây http://serverfault.com/questions/507375/nginx-not-finishing-fancyindex

**Comment by icy** [comment]
Cảm ơn @lokiheero  rất nhiều :)
