### ISSUE TITLE
bootstrap script

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#7]
- Write the bootstrap script

**Comment by NgoHuy** [comment]
It relates hooks. I will write some hooks to testing.

**Comment by icy** [comment]
Hiện tại quá trình `bootstrap` thực hiện từ `ArchLinux` chứ không phải `Debian` như dự kiến ban đầu. Sẽ xây dựng hệ thống `puppet` (hoặc tương tự) để quản lý cấu hình của các máy sử dụng.
