### ISSUE TITLE
Thử nghiệm hệ thống log-structured File System

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#71]
@NgoHuy  chú ý các vấn đề với nhiệt độ nhé.

Sau đó viết các tài liệu hướng dẫn cơ bản (dạng nội bộ, sau đó a sẽ giúp chuyển qua trang chủ sau.)

**Comment by NgoHuy** [comment]
Nhiệt độ máy (`cpu`) hay `usb` anh ơi ?

Hiện tại em không có cách gì đo nhiệt độ `usb` ngoài cách sờ

`hddtemp` không hỗ trợ `usb` anh ah

> sudo hddtemp /dev/sdb
> /dev/sdb: JetFlashTranscend 4GB:  drive supported, but it doesn't have a temperature sensor.

**Comment by icy** [comment]
ok bằng cách sờ thôi em :D Hoặc tìm trên mạng xem. Cần thì mua cái nhiệt kế về thử. Tại a thấy hình như nó hơi nóng mặc dù chả truy xuất gì. Không biết có phải vấn đề chung không.

**Comment by thuandt** [comment]
@NgoHuy Với HDD chỉ những device có support S.M.A.R.T thì mới lấy được nhiệt độ kiểu đó thôi, còn USB theo anh biết là không có cách nào để biết cả :3

**Comment by NgoHuy** [comment]
@mrtuxhdb vì `usb` bình thường không có cảm biến nhiệt anh ah :D

@icy em xác nhận không làm gì cũng nóng với cái `usb` của em :D

**Comment by icy** [comment]
Sao kỳ vậy ta. Không làm gì mà nó cũng nóng. Lâu nay đúng là không để ý. `usb` chỉ cần `mount` vào thôi cũng nóng sôi. tại sao?

**Comment by NgoHuy** [comment]
Em dự đóan do `usb` thường xuyên phải `khai báo` với `subsystem` của hệ thống nên dù không đọc ghi dữ liệu nhưng vẫn phải ở chế độ thường trực ( có thể điều chỉnh được  để tắt khi không làm gì )

**Comment by thuandt** [comment]
Chip nhớ của USB nó bé tí chạy hoài tất nhiên là phải nóng roài ;)

@NgoHuy HDD có cảm biến nhiệt mà smarttools nó hem support cũng như nhau mà

**Comment by icy** [comment]
@NgoHuy làm tới mức này rồi, đoán không ăn thua. Phải có bằng chứng và cơ chế rõ ràng em. Đừng đoán già đoán non nữa. Chả prof. tí nào.

**Comment by icy** [comment]
@mrtuxhdb Vậy vấn đề 'nóng' là vấn đề chung rồi, không tránh khỏi. Cũng lạ thật, mình không đủ các thông tin kỹ thuật giải thích việc này. Chẳng qua là lâu  nay không để ý, nên khi đụng tới `FS` mới lại bất ngờ :D 

@NgoHuy yên tâm kiểm tra tiếp về độ bề, khả năng tải của `FS` mới =)

**Comment by NgoHuy** [comment]
@icy theo cách họat động của `usb` mà em hiểu thỉ khi hệ thống không nằm trong chế độ tiết kiệm điện thì nó sẽ nằm trong chế độ thường trực nhận môt nguồn là 5V nên sinh nhiệt là bình thường :)

**Comment by icy** [comment]
@NgoHuy Nhớ cập nhật `status` nhé.

**Comment by NgoHuy** [comment]
Đây là bản theo dõi em ghi lại trong mây ngày qua trong quá trình sử dụng
- Xóa tập tin bằng tổ hợp lệnh “Shift + Delete” dung lượng trống không được trả lại
- Không ghi đè được dữ liệu khi thiếu chỗ trống ( dung lượng trống không được trả lại )
- Ghi lại tòan bộ các thay đổi trên filesystem có ngày giờ, chế độ, …
- Bất tiện phải tự xóa các thời điểm `checkpoint` ( cần một `cron job` xóa định kì hoặc luật xóa các checkpoint đã cũ khi có checkpoint mới tạo ra )
- Có thể `mount` từ bất cứ `checkpoint` nào đã có.
- Nhiệt độ mát hơn `ext4` khi ghi môt tập tin có kích thước tương đương ( hơn 700M)
- TODO : Thử mã hóa và ghi lại tốc độ, kiểm tra các `checkpoint`

**Comment by icy** [comment]
Cảm ơn @NgoHuy . Cái chỗ `mát hơn` này cũng hơi kỳ, nhưng cũng không quan trọng vì cả hai đều nóng :D

Hệ thống `LFS` sẽ không tự trả về khoảng trống, mà người dùng tự xử lý bằng tay. Em tìm thêm có giao diện nào phù hợp không. Nếu không có thể thử bắt đâu viết một ứng dụng nhỏ bằng `python-gtk` hoặc `ruby-gtk` anh nghĩ là đơn giản đấy :)

**Comment by NgoHuy** [comment]
Em không thấy giao diện nào phù hợp và đang viết ứng dụng nhỏ bằng `ruby-qt`  (hãy vui sông và chờ đợi :D )

**Comment by icy** [comment]
:D Có cập nhật gì không @NgoHuy  lâu ngày biến đâu mất thế.
