### ISSUE TITLE
Tài liệu dành cho Sponsor và  Partner

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#75]
Lâm coi chuẩn bị giúp các thông tin và tài liệu cho phần này nhé. Mình sẽ công bố chính thức trên trang chủ. Các thông tin mình sẽ giúp Lâm chuyển qua định dạng riêng của trang web sau.

Many thanks.

**Comment by vothailam** [comment]
Okie a.
lam.

On Saturday, July 6, 2013, Ky-Anh Huynh notifications@github.com wrote:

> Lâm coi chuẩn bị giúp các thông tin và tài liệu cho phần này nhé. Mình sẽ
> công bố chính thức trên trang chủ. Các thông tin mình sẽ giúp Lâm chuyển
> qua định dạng riêng của trang web sau.
> 
> Many thanks.
> 
> —
> Reply to this email directly or view it on GitHub.<
> https://github.com/notifications/beacon/CQ06EpqTp5UwllrWe2i6Z_huvvaEbd5bH6wdMv53_FtQuyIkow34b_kEpnJqfnQw.gif

## 

_Vo Thai Lam (Mr) | *_CEO**
**Mobile: (84) 90 38 39 390**
*
_Lac Tien Computing Joint Stock Company_*
Address:\* KC52/1/18 Huynh Tan Phat, Ward Tan Thuan Tay, Dist 7, Ho Chi Minh
City, Vietnam*
*_Phone:_ (84-8) 22 11 50 70 - Fax: (84-8) 6262 1286*
*
- Email:\* lienhe@lactien.com; contact@lactien.com*
  Website:\* http://www.lactien.com  | _Our
  community_:http://community.lactien.com

Founded on Oct. 2008, Lactien Computing JSC has many engineers graduated
from top universities in Vietnam. Our members are strongly experienced in
the field of Internet applications (corporate portal, e-commerce, online
services, online software etc.). Lactien is headquartered in Ho Chi Minh
City.
Our Products & Services: Bussines Applications (CRM, HRM, Project
Management system, eGroupware, ERP), Security & Network Solutions, Open
Source training.

**Comment by icy** [comment]
Các câu hỏi cần trả lời (cho cả Sponsor và Partner)
1. S/P là gì?
2. Ai và đơn vị nào có thể thành S/P? (Điều kiện, tư cách)
3. Các vấn đề có thể phát sinh?
4. Quyền lợi và nghĩa vụ cơ bản?
5. (bla bla)

**Comment by icy** [comment]
@vothailam  ơi có update gì không, a thêm vào comment này kẻo em nhiều việc quá quên mất. Thanks ^^

**Comment by vothailam** [comment]
Chắc cuối tuần này xong đó anh. Em cần tham khảo thêm vài mô hình nữa trước
khi đề xuát với mọi người.

**Comment by icy** [comment]
Assign => @icy để chuẩn bị và viết cái tài liệu từ các thông tin @vothailam đã giới thiệu
