### ISSUE TITLE
In áo/sticker #TheSLinux

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#76]
Bạn nào muốn in áo thì cho biết kich cỡ nhé . Tạm thời lấy số lượng đã :) Thiết kế tính sau ^^

**Comment by ck196** [comment]
+1&nbsp;

-- Sent from my Palm Pixi
On Jul 7, 2013 7:20 PM, Ky-Anh Huynh &lt;notifications@github.com&gt; wrote: 

Bạn nào muốn in áo thì cho biết kich cỡ nhé . Tạm thời lấy số lượng đã :) Thiết kế tính sau ^^

---

Reply to this email directly or view it on GitHub:
https://github.com/TheSLinux/gs/issues/76

**Comment by icy** [comment]
Có thể đặt làm mấy cái sticker dán linh tinh thay cho áo không nhỉ?

**Comment by icy** [comment]
Có thể đặt làm mấy cái sticker dán linh tinh thay cho áo không nhỉ?

**Comment by thuandt** [comment]
Mấy cái sticker thì làm nhanh thôi mà. Có mẫu đem ra hàng đánh roẹt cái là xong.

**Comment by icy** [comment]
Mấy trò này thì không rành. Chắc in áo sẽ hoãn lại hoặc dời qua đợt khác vì chi phí hơi cao, trong khi số lượng ít. Làm mấy cái sticker vui nhộn để dán linh tinh cũng được, mình cũng thích vậy hơn. Dán trên áo thì không biết có loại nào không. Để nhờ thêm mấy bạn giúp chứ mình nhiều việc quá :D

**Comment by icy** [comment]
@mitsukiAR Em làm giúp  nha như đã nói nha. Từ đây tới tháng 11 nên cũng không vội gì, nhưng nhớ sắp xếp làm kẻo quên. Làm cái `sticker` có kèm hình con gì với cái logo cho vui. Lưu ý là `logo` có hai bản khác nhau. Tông màu và các `logo` thì có ở `repo` riêng https://github.com/TheSLinux/media .

**Comment by thuandt** [comment]
Vote logo TheSLinux trên quả mít =]]

**Comment by icy** [comment]
Giống ... HIV quá vậy =))

**Comment by icy** [comment]
@mitsukiAR  Anh nhận link em gửi rồi. Chờ em online mà không thấy đâu. Khi nào tiện trao đổi thêm nhé . Cảm ơn em nhiều.

**Comment by icy** [comment]
Liên lạc với Khoa để hỗ trợ nơi in áo.
