### ISSUE TITLE
Vân đề an toàn của các máy build

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#77]
Hệ thống đóng gói sẽ có nhiều máy biên dịch (tạm gọi tên như vậy). Các máy này ban đầu sẽ dùng `ArchLinux` (ý định ban đầu sử dụng `Debian` không thành công do vướng nhiều vấn đề về thư viện liên kết). Một số máy thì có thể dùng `distro` khác (chỉ để cung cấp máy cho dãy `distcc`).

Các máy biên dịch sẽ ảnh hưởng tới toàn bộ bản phân phối `theslinux`. Nếu một trong các máy biên dịch gặp phải các vấn đề về hệ thống, bảo mật,... thì các gói do nó sinh ra cũng có thể là nguồn phát tán các con sâu!

Bài toán:
1. Đặt ra các tiêu chuẩn về hệ thống và an toàn cơ bản cho các máy biên dịch.
2. Đặt ra cơ chế kiểm tra định kỳ phát hiện lỗi và kiểm soát các vấn đề của máy biên dịch.

**Comment by NgoHuy** [comment]
Vấn đề này em sẽ chịu trách nhiệm, hẹn găp tại party keysigning  :-)

**Comment by icy** [comment]
On Fri, 16 Aug 2013 08:06:09 -0700
Ngô Huy notifications@github.com wrote:

> Vấn đề này em sẽ chịu trách nhiệm, hẹn găp tại party keysigning  :-)

Cái này a cũng để ở `low priority` (em chú ý hướng dẫn ở phần README nhé [1]). Em có thể giới thiệu, mời các bạn tham gia vào, nhất là các bạn có kinh nghiệm. Việc ai chịu trách nhiệm thì chưa cần nói tới (em không đủ sức cho phần này, a cũng thế, qua to lớn. Từ từ làm.)

[1] https://github.com/TheSLinux/gs

## 

I am ... 5.5 dog years old.

**Comment by icy** [comment]
Trao đổi trên nhóm thư http://www.mail-archive.com/questions@lists.theslinux.org/msg00022.html
