### ISSUE TITLE
Viết tài liệu / chương trình (GUI) giao diện cho nilfs

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#82]
`nilfs` không có giao diện đồ họa, có thể viết một chương trình đơn giản, ví dụ bằng `qt` hoặc `libncurses` để quản lý các `check-points`.

Nhưng đầu tiên là phải chuẩn bị một tài liệu thật tốt cho `nilfs`

**Comment by icy** [comment]
cc @NgoHuy . Phần thử nghiệm có ở #71

**Comment by NgoHuy** [comment]
Em đã viết bằng `qtruby` tuy nhiên gặp phải vấn đề với `signal` và `slot` nên đã `port` lại sang `gtk` đã được 1/3 tính năng là `format` còn `view` nữa. Sẽ xong trong tháng này !

**Comment by icy** [comment]
Mất công thế =)

Cần chuẩn bị tài liệu nữa nha, việc này hơi khó và mất công. Em có thể viết sơ lược a giúp chuyển qua hệ thống `homepage`.

**Comment by thuandt** [comment]
signal và slot thì có gì đâu mà phải xoắn đến mức xài GTK+ ta :3

**Comment by NgoHuy** [comment]
Qua cái này mới thấy mình tệ thế nào, đọc một `framework` không xong :( 

Đây là sơ bộ cho tính nằng `format`  [1]

`TODO` `view, create, delete checkpoint`  

[1] : https://github.com/NgoHuy/buildsystem/commit/c481ceba5e6c9ae9ce5b4237bb7f9eccee264b38

**Comment by icy** [comment]
Về kết quả thì mới nhìn qua a thấy tương đối, nhưng chưa rõ các ý đồ
và hỗ trợ của chương trình này thế nào. Té ra em vẫn dùng `gtk` binding
trong `ruby`, a tưởng em dùng `c/gtk` luôn chứ hihi. Anh nghĩ e viết
các mô tả của chương trình trước, ví dụ nó sẽ làm gì, các bước nhập
thế nào, v.v...

Bữa nào Huy với các bạn họp lại mình hướng dẫn về `buildsystem` và `nanoc`
và các thứ khác. Làm việc tốt mà trình bày mã và nhiều vấn đề khác còn
chưa tốt lắm. `buildsystem` chỉ dành để đóng gói. Với các phần mềm hay
tiện ích mới viết thêm, thì nên để ở kho riêng của em, hoặc `theslinux-forks`
(nhưng hiện nay a đang tính bỏ luôn nhóm này.)

Thanks again,

**Comment by NgoHuy** [comment]
Xác nhận em không thể xử lý đươc mục `view` để xem các `checkpoint` trong chương trình các tính năng khác vẫn làm được.

**Comment by icy** [comment]
... tài liệu :D

**Comment by icy** [comment]
Huy làm cái khác còn nhiều việc, cái gì khó tạm gác qua bên từ từ sẽ giải quyết được.
