### ISSUE TITLE
Chuẩn bị lại môi trường build

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#84]
Liên quan: #77 , #8 
CC: @xluffy 

Cần chuẩn bị lại môi trường build dựa trên Debian. Câu hỏi đầu tiên là có thể tạo môi trường `chroot` để build hệ thống `Arch` hay không. Các bước kiểm tra
1. cài debian 7
2. cài arch vào (dạng chroot)
3. build một số lib của arch (glibc chẳng hạn)

Mục tiêu là có thể đi tới được bước thứ 3, biên dịch thành công `glibc` (xem thêm các bước trong https://github.com/TheSLinux/buildsystem/blob/glibc/glibc/PKGBUILD )

Công cụ `bootstrap`: https://github.com/tokland/arch-bootstrap

**Comment by icy** [comment]
A cần @xluffy  giúp các bước kiểm tra. Việc chuẩn bị môi trường `build` thật sự sẽ tiến hành sau, với các tài liệu chi tiết hơn. Nếu có máy thật thì sẽ làm nhanh. Trong quá trình `bootstrap` có thắc mắc gì thì hỏi anh có thể giúp (do a đã làm cái này nhiều lần :D). Về `mirror` có thể sử dụng FPT do đã chỉnh xong lỗi kết nối chậm (#68)

**Comment by thuandt** [comment]
@icy Với Ubuntu 13.04 thì em khẳng định là `bootstrap` được vào `Arch` vì em đã làm cách đây mấy tháng rồi.

**Comment by icy** [comment]
Cảm ơn @thuandt mình sẽ coi xem có nên dùng Ubuntu được không :)

**Comment by NgoHuy** [comment]
Em đã `bootrap` và `build` thành công gói `glibc` và có những ghi chú sau
- Phải `mount devpts` để tránh lỗi `GPGME error: Inappropriate ioctl for device`
- Thêm các gói sau vào `base packages`
  - gcc 
  - fakeroot
  - patch
  - make
  - diffutils

**Comment by icy** [comment]
Okay, việc chạy một bộ `arch` (chroot) bên trong `Debian` không phải là vấn đề quá khó khăn. Một vấn đề khác là biên dịch một số gói cơ bản ngay bên trong `Debian` luôn mới điên đầu. Cái này sẽ thử làm trong tương lai gần, tạm thời chưa quan tâm.

**Comment by NgoHuy** [comment]
Việc tốt nhất em có thể làm cho dự án vẫn là đóng gói và kiểm tra môi trường build, em sẽ chịu trách nhiệm vấn đề này tốt hơn và thường xuyên cập nhật trạng thái trên github :-)

**Comment by NgoHuy** [comment]
Sau một thời gian cài và chạy thử em có vài quan điểm như sau
- Môi trường biên dịch  phải là môi trường nguyên bản của bản phân phối, tức là TheSlinux không `chroot` hay môi trường nào khác, em đã thử chạy trực tiếp Arch bên trong Debian được nhưng không đảm bảo được sự ổn định cũng như các vấn đề biên dich, liên kết thư viện của gói sinh ra cũng như phải vá khá nhiều chỗ.
- Em chưa hiểu rõ lắm mô hình phân phối gói tới các repo, nếu em không lầm thì có thể đề xuất cơ chế sau để kiểm tra định kì các máy biên dịch để tránh nguồn phát tán sâu
  - Máy biên dịch chỉ có thể biên dịch và tải mã nguồn từ kho khác, nếu có mã độc thì chỉ có 3 khả năng  : mã nguồn có độc hoăc các bản cập nhật bị thay đổi thêm mã độc ( khó hơn vì đã được kí ) và máy của nhà phát triển bị tấn công tải mã độc lên qua `ssh`
  - Trong quá trình phân phối các máy trạm có thể bị tấn công thay đổi gói, nguy cơ này cao nhưng có thể bị chặn bởi chữ kí,

Vậy câu hỏi phải là khi phát hiện mã nguồn có mã độc phải xử lý thế nào, và cơ chế kí, biên dịch tự động hay biên dịch thủ công, vá sẽ như thế nào ?

**Comment by icy** [comment]
On Fri, 16 Aug 2013 07:16:52 -0700
Ngô Huy notifications@github.com wrote:

> Sau một thời gian cài và chạy thử em có vài quan điểm như sau
> - Môi trường biên dịch  phải là môi trường nguyên bản của bản phân
>   phối, tức là TheSlinux không `chroot` hay môi trường nào khác, em đã
>   thử chạy trực tiếp Arch bên trong Debian được nhưng không đảm bảo
>   được sự ổn định cũng như các vấn đề biên dich, liên kết thư viện của
>   gói sinh ra cũng như phải vá khá nhiều chỗ.

Cái này từ từ làm cũng được. (Anh đã đánh dấu "low priority").

> - Em chưa hiểu rõ lắm mô hình phân phối gói tới các repo, nếu em
>   không lầm thì có thể đề xuất cơ chế sau để kiểm tra định kì các máy
>   biên dịch để tránh nguồn phát tán sâu
>   - Máy biên dịch chỉ có thể biên dịch và tải mã nguồn từ kho khác,
>     nếu có mã độc thì chỉ có 3 khả năng  : mã nguồn có độc hoăc các bản
>     cập nhật bị thay đổi thêm mã độc ( khó hơn vì đã được kí ) và máy của
>     nhà phát triển bị tấn công tải mã độc lên qua `ssh`
>   - Trong quá trình phân phối các máy trạm có thể bị tấn công thay
>     đổi gói, nguy cơ này cao nhưng có thể bị chặn bởi chữ kí,
> 
> Vậy câu hỏi phải là khi phát hiện mã nguồn có mã độc phải xử lý thế
> nào, và cơ chế kí, biên dịch tự động hay biên dịch thủ công, vá sẽ
> như thế nào ?

Keysiging party là một phần trong quy trình. Có chủ đề riêng về vấn đề
an toàn của các máy biên dịch. Anh không rõ là chủ đề nào, em có thể tìm
trong phần gắn nhãn "Security", bàn luận ở đó nhé. Các vấn đề an toàn
cần làm từ từ, lâu dài, ổn định.

Tạm thời phần môi trường `build` này tạm ổn, sẽ dùng arch để build ra hệ
thống Arch. Sắp tới có thể mua thêm một máy tính 8 nhân, AMD , tốn chừng
6 hoặc 7 triệu hết chi phí. Em có thời gian rảnh thì chạy qua chỗ nhà anh
phụ ráp và cài đặt máy. Nhà anh gần chỗ quán Lucky hồi xưa. Kế hoạch là 
cuối tháng này đi mua, qua tháng tới sẽ tiến hành build liên tục các gói
dự kiến khoảng 900 hoặc 1000 gói đầu tiên. 

Số builder dự tính là 2 (tổng số core = 12), do anh đang dùng một con 4 core.

**Comment by icy** [comment]
Đang lập môi trường biên dịch mới trên máy `phant6m` http://m3.theslinux.org/l00s/6r/

**Comment by icy** [comment]
Máy `phant6m` tạm thời không được sử dụng làm môi trường biên dịch cuối cùng, mà để dành cho việc biên dịch thử nghiệm, và cung cấp môi trường làm việc cho các thành viên của dự án. Xem thêm phần lịch sử ở trang riêng của máy `phant6m`.
