### ISSUE TITLE
tiny, l00s5r: clean up

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#89]
Xem #67 và #88 .

Hai máy `debian` này sau khi nâng cấp lên bản `7.1` thì có rất nhiều gói trời ơi đất hỡi được cài vào, ví dụ các gói ứng dụng `X`, giờ phải mày mò gỡ bỏ hết ra cho có thêm nhiều khoảng trống.

**Comment by icy** [comment]
Trên `tiny` còn có cả thư viện xử lý tiếng Thái Lan. Hết chịu nổi!

**Comment by thuandt** [comment]
x11-common thì khi cài một số fonts vào nó cũng kéo theo mà.
Tụi này chiếm không nhiều space đâu, đống locale/docs/man chiếm mới nhiều

**Comment by icy** [comment]
Mấy chú `doc`, `man`, `locales` a ngồi vặt bằng tay hết rồi. Có cái `localpurge` mà cũng chưa bao giờ cài thử keke

**Comment by thuandt** [comment]
`localepurge` xài nhanh hơn mà, config một lát. Chạy lệnh là có clean sạch.
Như em là mỗi lần cài cái gì localepurge nó tự clean luôn.

**Comment by icy** [comment]
Anh biết gói này đã lâu mà trên Arch hay Debian không có sẵn gói nên chả xài :D Giờ a không dùng `AUR` nữa keke

**Comment by icy** [comment]
Anh đang nghĩ tới cách `purge` từ lúc `build` ra các gói luôn (có thể thay vì dọn sạch thì tách ra từng gói nhỏ). Câu hỏi là (1) làm thế có phát sinh các vấn đề bản quyền không (nếu có thì cũng không phải là không làm được, nhưng cần biết để xử lý sự cố), (2) làm thế có bất tiện gì không?

**Comment by thuandt** [comment]
`localepurge` là gói có sẵn trong debian mà :)

Còn về câu hỏi `purge` lúc build thì em nghĩ không có vấn đề gì về bản quyền, còn sự bất tiện nó chỉ xảy ra khi người dùng dùng `locale` khác. Mình không purge `en_US` và `vn_VN` thì không có vấn đề gì cả.

**Comment by icy** [comment]
À thấy rồi. Bên Arch thì gói `aur` cũng lấy gói của `Debian` về xử lại.

**Comment by icy** [comment]
- Gỡ hết mấy bộ `python` trên máy `tiny`
- Gỡ hết các bộ `python` (trừ bộ `python2.7-minimal` để chạy con `bot`

**Comment by icy** [comment]
- Trên máy `tiny` (kiến trúc `i586`), khi cài `libc6-dev` vào có thư mục to cỡ 10M là `/usr/lib/i386-linux-gnu/xen/` . Xóa :)
- Không hiểu vì lý do gì trên cả `tiny` và `l00s5r` có rất nhiều bộ `python` và `ruby` khác nhau. Phần `python` đã gỡ như đã nói ở trên. Phần ruby thì điều lạ là `ruby1.9.3` khi cài vào sẽ kéo nguyên cả họ `X11-common` và ba thứ linh tinh vào nữa. Nếu cài `ruby1.9.1` sẽ không có hiện tượng kéo chùm này. Tạm thời bỏ qua phiên bản `1.9.3`

**Comment by icy** [comment]
Trên `tiny`, bỏ đi các thư mục `spec`, `examples`, `tests`, ... trong các thư mục `gem` (ví dụ `puppet`) cũng giải quyết được kha khá không gian đĩa :)

**Comment by icy** [comment]
Trên `tiny`, gỡ bỏ `cpp-4.6`, `cpp-4.4` (cài vô làm gì đây nhỉ!?) Thật là khỏe, giờ còn được `292 MB` đĩa trống ^^

**Comment by icy** [comment]
Tạm thời ổn, đóng topic lại.

**Comment by icy** [comment]
- tiny: gỡ bỏ các gói `dovecot-{sqlite,mysql,pgsql,ldap,gssapi,sieve}`

**Comment by icy** [comment]
- label Weekly.

**Comment by icy** [comment]
Cần kiểm soát lúc cài vào.
