### ISSUE TITLE
The Keysigning Party

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#90]
CC: @lokiheero @NgoHuy  @gialachoanglong @xluffy @mitsukiAR 

Thời gian dự kiến: 11/8 hoặc 18/8 . Trao đổi thêm trên #theslinux và #archlinuxvn.

Tham khảo http://www.cryptnet.net/fdp/crypto/keysigning_party/en/keysigning_party.html

Bài liên quan: #78

**Comment by icy** [comment]
Tài liệu về GPG http://archlinuxvn.org/doc/security/gpg/

**Comment by icy** [comment]
CC: @n0b0dyvn @dynamo1411 @thuandt

**Comment by n0b0dyvn** [comment]
11 với 12 em bận nha :D

**Comment by icy** [comment]
Chưa có ngày cụ thể @n0b0dyvn , có gì để @xluffy  làm cái chọn để bà con vào lựa thôi.

**Comment by viethuynhvn** [comment]
:+1:  Đăng ký tham gia :)

**Comment by icy** [comment]
Okay Việt, chờ các bạn chuẩn bị và thông báo về sự kiện nhé.!

**Comment by icy** [comment]
Tạm thời phân công việc
1. @xluffy : Chuẩn bị mô tả, `doodle`, đối tượng, mục đích tham gia, quy mô tổ chức, thời gian, địa điểm.
2. @icy vaf @xluffy : thông báo trên các kênh thư, Facebook và twitter
3. @n0b0dyvn  và @icy: chuẩn bị tài liệu, `cheatsheet` để có thể sử dụng nhanh trong `party`

**Comment by icy** [comment]
Thông báo chính thức trên trang chủ http://theslinux.org/events/2013/08-keysigning-party/

**Comment by icy** [comment]
Hôm này chỉ có 6 bạn tham gia (Long và bạn, @n0b0dyvn, @xluffy , @NgoHuy và /me). Nội dung chỉ là trao đổi. Trừ Huy và /me có dùng thường xuyên các bạn khác thì ... hầu như không dùng. Huy không mang máy tính nên cũng không `sign` gì được. Hẹn lần `signing` kế tiếp, có thể là ở `SFD` vào cuối tháng 9.
