### ISSUE TITLE
Cải tiến / thay đổi biểu tượng của `uim` trên `systray`

### ISSUE THREAD

**Issue by icy** [TheSLinux/gs#91]
Trên nhiều giao diện đồ họa, biểu tượng của `uim` trên `systray` rất khó theo dõi, do có tới hai biểu tượng (một cái dành cho trạng thái, một cái dành cho kiểu gõ).

Có cách nào để làm rõ các biểu tượng hoặc bớt đi một trong các biểu tượng không?

**Comment by icy** [comment]
@NgoHuy  coi qua mã nguồn của `uim` phần dành cho `gtk2 / systray`. Anh mới nhìn thoáng sơ trong 2 ngày qua mà chưa phát hiện cách để tạm bỏ đi biểu tượng thứ hai chỉ trạng thái của bộ gõ. Để thay đổi và thử mã nguồn em `uim` sẽ sử dụng

```
s-makepkg --skipchecksums --noextract  -f
```

và có thể tạm `comment` các dòng tạo miếng vá và `autogen.sh`, `configure` để đỡ mất công chờ.

**Comment by icy** [comment]
Anh làm được rồi, @NgoHuy  khỏi lo :D

**Comment by NgoHuy** [comment]
em tưởng anh gửi lâu chứ mới hồi sáng, em không kiểm tra thư hehe

**Comment by icy** [comment]
Fix trong
- https://github.com/TheSLinux/buildsystem/commit/d6f888efc2b0b4c25283356a552e3ef8970ee1d4
- Gói dành cho máy 64 bit: [1] , chữ ký [2]

[1] http://mirror-fpt-telecom.fpt.net/theslinux/testing/uim-vi-1.8.5-41-x86_64.pkg.tar.xz 
[2] http://mirror-fpt-telecom.fpt.net/theslinux/testing/uim-vi-1.8.5-41-x86_64.pkg.tar.xz
